extends Node
## DCSS-based tile mapper for Necromancer
## Auto-generated by process_dcss_tiles.py
## Tileset: 32x32 grid of 64x64 tiles (2048x2048 pixels)

# Coordinate lookup tables
var terrain_coords: Dictionary = {}
var monster_coords: Dictionary = {}
var item_coords: Dictionary = {}
var artifact_coords: Dictionary = {}
var player_coords: Dictionary = {}
var effect_coords: Dictionary = {}

# Monster display char to ID mapping (for existing code compatibility)
var char_to_monster_id: Dictionary = {}

func _ready() -> void:
    _load_terrain_coords()
    _load_monster_coords()
    _load_item_coords()
    _load_artifact_coords()
    _load_player_coords()
    _load_effect_coords()
    _load_char_mappings()
    print("=== TileMapper Initialized (DCSS Tiles) ===")
    print("Grid: 32x32, Tile size: 64x64")
    print("Total tiles loaded: ", terrain_coords.size() + monster_coords.size() + item_coords.size())

func _load_terrain_coords() -> void:
    # Format: terrain_coords[id] = {"light": Vector2i, "dark": Vector2i}
    terrain_coords[0] = {"light": Vector2i(0, 0), "dark": Vector2i(1, 0)}  # darkness
    terrain_coords[1] = {"light": Vector2i(2, 0), "dark": Vector2i(3, 0)}  # open floor
    terrain_coords[4] = {"light": Vector2i(4, 0), "dark": Vector2i(5, 0)}  # open door
    terrain_coords[6] = {"light": Vector2i(6, 0), "dark": Vector2i(7, 0)}  # warded door
    terrain_coords[7] = {"light": Vector2i(8, 0), "dark": Vector2i(9, 0)}  # warded door
    terrain_coords[8] = {"light": Vector2i(10, 0), "dark": Vector2i(11, 0)}  # warded door
    terrain_coords[9] = {"light": Vector2i(12, 0), "dark": Vector2i(13, 0)}  # fading daylight
    terrain_coords[10] = {"light": Vector2i(14, 0), "dark": Vector2i(15, 0)}  # open floor
    terrain_coords[11] = {"light": Vector2i(16, 0), "dark": Vector2i(17, 0)}  # wall
    terrain_coords[13] = {"light": Vector2i(18, 0), "dark": Vector2i(19, 0)}  # morgul runes
    terrain_coords[15] = {"light": Vector2i(20, 0), "dark": Vector2i(21, 0)}  # torture rack
    terrain_coords[17] = {"light": Vector2i(22, 0), "dark": Vector2i(23, 0)}  # jagged pit
    terrain_coords[18] = {"light": Vector2i(24, 0), "dark": Vector2i(25, 0)}  # poisoned spike pit
    terrain_coords[19] = {"light": Vector2i(26, 0), "dark": Vector2i(27, 0)}  # poison needle trap
    terrain_coords[22] = {"light": Vector2i(28, 0), "dark": Vector2i(29, 0)}  # orc alarm
    terrain_coords[24] = {"light": Vector2i(30, 0), "dark": Vector2i(31, 0)}  # rusted caltrops
    terrain_coords[26] = {"light": Vector2i(0, 1), "dark": Vector2i(1, 1)}  # thick web
    terrain_coords[29] = {"light": Vector2i(2, 1), "dark": Vector2i(3, 1)}  # prison bars
    terrain_coords[32] = {"light": Vector2i(4, 1), "dark": Vector2i(5, 1)}  # iron door
    terrain_coords[50] = {"light": Vector2i(6, 1), "dark": Vector2i(7, 1)}  # unused
    terrain_coords[51] = {"light": Vector2i(8, 1), "dark": Vector2i(9, 1)}  # quartz vein
    terrain_coords[52] = {"light": Vector2i(10, 1), "dark": Vector2i(11, 1)}  # unused
    terrain_coords[53] = {"light": Vector2i(12, 1), "dark": Vector2i(13, 1)}  # unused
    terrain_coords[54] = {"light": Vector2i(14, 1), "dark": Vector2i(15, 1)}  # unused
    terrain_coords[55] = {"light": Vector2i(16, 1), "dark": Vector2i(17, 1)}  # unused
    terrain_coords[56] = {"light": Vector2i(18, 1), "dark": Vector2i(19, 1)}  # dark stone wall
    terrain_coords[57] = {"light": Vector2i(20, 1), "dark": Vector2i(21, 1)}  # dark stone wall
    terrain_coords[58] = {"light": Vector2i(22, 1), "dark": Vector2i(23, 1)}  # dark stone wall
    terrain_coords[59] = {"light": Vector2i(24, 1), "dark": Vector2i(25, 1)}  # dark stone wall
    terrain_coords[60] = {"light": Vector2i(26, 1), "dark": Vector2i(27, 1)}  # unused
    terrain_coords[61] = {"light": Vector2i(28, 1), "dark": Vector2i(29, 1)}  # unused
    terrain_coords[62] = {"light": Vector2i(30, 1), "dark": Vector2i(31, 1)}  # unused
    terrain_coords[63] = {"light": Vector2i(0, 2), "dark": Vector2i(1, 2)}  # dark stone wall
    terrain_coords[64] = {"light": Vector2i(2, 2), "dark": Vector2i(3, 2)}  # orc forge (exhausted)
    terrain_coords[65] = {"light": Vector2i(4, 2), "dark": Vector2i(5, 2)}  # orc forge (1 use remaining)
    terrain_coords[66] = {"light": Vector2i(6, 2), "dark": Vector2i(7, 2)}  # orc forge (2 uses remaining)
    terrain_coords[67] = {"light": Vector2i(8, 2), "dark": Vector2i(9, 2)}  # orc forge (3 uses remaining)
    terrain_coords[68] = {"light": Vector2i(10, 2), "dark": Vector2i(11, 2)}  # orc forge (4 uses remaining)
    terrain_coords[69] = {"light": Vector2i(12, 2), "dark": Vector2i(13, 2)}  # orc forge (5 uses remaining)
    terrain_coords[70] = {"light": Vector2i(14, 2), "dark": Vector2i(15, 2)}  # shadow forge (exhausted)
    terrain_coords[71] = {"light": Vector2i(16, 2), "dark": Vector2i(17, 2)}  # shadow forge (1 use remaining)
    terrain_coords[72] = {"light": Vector2i(18, 2), "dark": Vector2i(19, 2)}  # shadow forge (2 uses remaining)
    terrain_coords[73] = {"light": Vector2i(20, 2), "dark": Vector2i(21, 2)}  # shadow forge (3 uses remaining)
    terrain_coords[74] = {"light": Vector2i(22, 2), "dark": Vector2i(23, 2)}  # shadow forge (4 uses remaining)
    terrain_coords[75] = {"light": Vector2i(24, 2), "dark": Vector2i(25, 2)}  # shadow forge (5 uses remaining)
    terrain_coords[76] = {"light": Vector2i(26, 2), "dark": Vector2i(27, 2)}  # forge Angdur (exhausted)
    terrain_coords[77] = {"light": Vector2i(28, 2), "dark": Vector2i(29, 2)}  # forge Angdur (1 use remaining)
    terrain_coords[78] = {"light": Vector2i(30, 2), "dark": Vector2i(31, 2)}  # forge Angdur (2 uses remaining)
    terrain_coords[79] = {"light": Vector2i(0, 3), "dark": Vector2i(1, 3)}  # forge Angdur (3 uses remaining)
    terrain_coords[80] = {"light": Vector2i(2, 3), "dark": Vector2i(3, 3)}  # crumbling stairs up
    terrain_coords[81] = {"light": Vector2i(4, 3), "dark": Vector2i(5, 3)}  # dark stairs down
    terrain_coords[82] = {"light": Vector2i(6, 3), "dark": Vector2i(7, 3)}  # narrow shaft up
    terrain_coords[83] = {"light": Vector2i(8, 3), "dark": Vector2i(9, 3)}  # narrow shaft down
    terrain_coords[87] = {"light": Vector2i(10, 3), "dark": Vector2i(11, 3)}  # forest floor

    # Level.gd Tile enum compatibility mappings
    # These alias the simple enum values to appropriate DCSS tiles
    terrain_coords[2] = {"light": Vector2i(16, 0), "dark": Vector2i(17, 0)}  # WALL = 2 -> wall (same as 11)
    terrain_coords[3] = {"light": Vector2i(4, 1), "dark": Vector2i(5, 1)}    # DOOR_CLOSED = 3 -> iron door (same as 32)
    terrain_coords[5] = {"light": Vector2i(4, 3), "dark": Vector2i(5, 3)}    # STAIRS_DOWN = 5 -> dark stairs down (same as 81)
    # Overwrite conflicting IDs 6-9 for level.gd compatibility
    terrain_coords[6] = {"light": Vector2i(2, 3), "dark": Vector2i(3, 3)}    # STAIRS_UP = 6 -> crumbling stairs up (same as 80)
    terrain_coords[7] = {"light": Vector2i(22, 0), "dark": Vector2i(23, 0)}  # CHASM = 7 -> jagged pit (same as 17)
    terrain_coords[8] = {"light": Vector2i(2, 0), "dark": Vector2i(3, 0)}    # RUBBLE = 8 -> open floor (same as 1)
    terrain_coords[9] = {"light": Vector2i(12, 2), "dark": Vector2i(13, 2)}  # FORGE = 9 -> orc forge 5 uses (same as 69)

func _load_monster_coords() -> void:
    monster_coords[0] = Vector2i(16, 3)  # player (Elf)
    monster_coords[1] = Vector2i(17, 3)  # player (Man)
    monster_coords[2] = Vector2i(18, 3)  # player (Dwarf)
    monster_coords[11] = Vector2i(19, 3)  # Mirkwood Spider
    monster_coords[12] = Vector2i(20, 3)  # Giant Rat
    monster_coords[13] = Vector2i(21, 3)  # Black Squirrel
    monster_coords[14] = Vector2i(22, 3)  # Crebain
    monster_coords[15] = Vector2i(23, 3)  # Tanglethorn
    monster_coords[16] = Vector2i(24, 3)  # Giant Bat
    monster_coords[17] = Vector2i(25, 3)  # Web Spinner
    monster_coords[18] = Vector2i(26, 3)  # Orc Scout
    monster_coords[19] = Vector2i(27, 3)  # Swamp Adder
    monster_coords[20] = Vector2i(28, 3)  # Great Spider
    monster_coords[21] = Vector2i(29, 3)  # Warg Pup
    monster_coords[31] = Vector2i(30, 3)  # Orc Slave
    monster_coords[32] = Vector2i(31, 3)  # Orc Soldier
    monster_coords[33] = Vector2i(0, 4)  # Orc Crossbowman
    monster_coords[34] = Vector2i(1, 4)  # Warg
    monster_coords[35] = Vector2i(2, 4)  # Orc Thrallmaster
    monster_coords[36] = Vector2i(3, 4)  # Orc Captain
    monster_coords[37] = Vector2i(4, 4)  # Warg Rider
    monster_coords[38] = Vector2i(5, 4)  # Hill Troll
    monster_coords[39] = Vector2i(6, 4)  # Gashnak, Warg-lord
    monster_coords[40] = Vector2i(7, 4)  # Orc Warchief
    monster_coords[51] = Vector2i(8, 4)  # Dark Acolyte
    monster_coords[52] = Vector2i(9, 4)  # Ghoul
    monster_coords[53] = Vector2i(10, 4)  # Mirk-troll
    monster_coords[55] = Vector2i(11, 4)  # Dark Sorcerer
    monster_coords[58] = Vector2i(12, 4)  # Ghast
    monster_coords[59] = Vector2i(13, 4)  # Karvag the Torturer
    monster_coords[71] = Vector2i(14, 4)  # Skeleton
    monster_coords[72] = Vector2i(15, 4)  # Skeleton Warrior
    monster_coords[73] = Vector2i(16, 4)  # Zombie
    monster_coords[74] = Vector2i(17, 4)  # Wight
    monster_coords[76] = Vector2i(18, 4)  # Necromancer Adept
    monster_coords[79] = Vector2i(19, 4)  # Grishnakh, Crypt Lord
    monster_coords[91] = Vector2i(20, 4)  # Phantom
    monster_coords[92] = Vector2i(21, 4)  # Shadow
    monster_coords[93] = Vector2i(22, 4)  # Whispering Shade
    monster_coords[94] = Vector2i(23, 4)  # Wraith
    monster_coords[95] = Vector2i(24, 4)  # Fell Spirit
    monster_coords[97] = Vector2i(25, 4)  # Vampire Thrall
    monster_coords[111] = Vector2i(26, 4)  # Black Numenorean
    monster_coords[112] = Vector2i(27, 4)  # Olog-hai
    monster_coords[113] = Vector2i(28, 4)  # Vampire
    monster_coords[115] = Vector2i(29, 4)  # Vampire Lord
    monster_coords[117] = Vector2i(30, 4)  # Maia Thrall
    monster_coords[131] = Vector2i(31, 4)  # Elite Olog-hai
    monster_coords[132] = Vector2i(0, 5)  # Greater Shadow
    monster_coords[134] = Vector2i(1, 5)  # Thrain's Shade
    monster_coords[135] = Vector2i(2, 5)  # Sauron, the Necromancer
    monster_coords[301] = Vector2i(3, 5)  # Gandalf the Grey
    monster_coords[304] = Vector2i(4, 5)  # Elrond Half-elven
    monster_coords[305] = Vector2i(5, 5)  # Thorin Oakenshield
    monster_coords[306] = Vector2i(6, 5)  # Beorn the Skinchanger
    monster_coords[307] = Vector2i(7, 5)  # Radagast the Brown

func _load_item_coords() -> void:
    item_coords[6] = Vector2i(8, 5)  # Necklace
    item_coords[20] = Vector2i(9, 5)  # Massive Iron Crown
    item_coords[21] = Vector2i(10, 5)  # Elven Light
    item_coords[22] = Vector2i(11, 5)  # Wanderer's Robe
    item_coords[23] = Vector2i(12, 5)  # Ranger Leathers
    item_coords[26] = Vector2i(13, 5)  # Scout's Armor
    item_coords[27] = Vector2i(14, 5)  # Shadow-steel Armor
    item_coords[30] = Vector2i(15, 5)  # Gondor Corslet
    item_coords[31] = Vector2i(16, 5)  # Dwarven Hauberk
    item_coords[38] = Vector2i(17, 5)  # Mithril Corslet
    item_coords[40] = Vector2i(18, 5)  # Orc Skeleton
    item_coords[41] = Vector2i(19, 5)  # Human Skeleton
    item_coords[42] = Vector2i(20, 5)  # Elf Skeleton
    item_coords[43] = Vector2i(21, 5)  # Buckler
    item_coords[44] = Vector2i(22, 5)  # Tower Shield
    item_coords[46] = Vector2i(23, 5)  # Mithril Shield
    item_coords[56] = Vector2i(24, 5)  # Ranger's Knife
    item_coords[57] = Vector2i(25, 5)  # Orc-blade
    item_coords[60] = Vector2i(26, 5)  # Woodland Blade
    item_coords[64] = Vector2i(27, 5)  # Longsword
    item_coords[67] = Vector2i(28, 5)  # Rohirrim Blade
    item_coords[68] = Vector2i(29, 5)  # Numenorean Blade
    item_coords[69] = Vector2i(30, 5)  # Mithril Sword
    item_coords[70] = Vector2i(31, 5)  # Mithril Great-blade
    item_coords[71] = Vector2i(0, 6)  # Hunting Spear
    item_coords[72] = Vector2i(1, 6)  # Tower Guard Spear
    item_coords[74] = Vector2i(2, 6)  # Morgul Glaive
    item_coords[76] = Vector2i(3, 6)  # Woodsman's Axe
    item_coords[77] = Vector2i(4, 6)  # Dwarven War-axe
    item_coords[81] = Vector2i(5, 6)  # Erebor Great-axe
    item_coords[86] = Vector2i(6, 6)  # Oak Staff
    item_coords[98] = Vector2i(7, 6)  # Dwarf Mattock
    item_coords[100] = Vector2i(8, 6)  # Iron Helm
    item_coords[101] = Vector2i(9, 6)  # Tower Helm
    item_coords[103] = Vector2i(10, 6)  # Mithril Helm
    item_coords[104] = Vector2i(11, 6)  # Crown
    item_coords[106] = Vector2i(12, 6)  # Traveler's Cloak
    item_coords[107] = Vector2i(13, 6)  # Shadow Cloak
    item_coords[108] = Vector2i(14, 6)  # Wolf-Hame
    item_coords[109] = Vector2i(15, 6)  # Bat-Fell
    item_coords[116] = Vector2i(16, 6)  # Arrow
    item_coords[122] = Vector2i(17, 6)  # Traveler's Boots
    item_coords[123] = Vector2i(18, 6)  # Iron Greaves
    item_coords[124] = Vector2i(19, 6)  # Mithril Greaves
    item_coords[125] = Vector2i(20, 6)  # Leather Gloves
    item_coords[126] = Vector2i(21, 6)  # Iron Gauntlets
    item_coords[127] = Vector2i(22, 6)  # Mithril Gauntlets
    item_coords[128] = Vector2i(23, 6)  # Wooden Torch
    item_coords[129] = Vector2i(24, 6)  # Brass Lantern
    item_coords[132] = Vector2i(25, 6)  # Last Chances (staff)
    item_coords[133] = Vector2i(26, 6)  # Constitution (staff)
    item_coords[134] = Vector2i(27, 6)  # Grace (staff)
    item_coords[135] = Vector2i(28, 6)  # Regeneration (staff)
    item_coords[136] = Vector2i(29, 6)  # Preservation (staff)
    item_coords[137] = Vector2i(30, 6)  # the Blessed Realm (staff)
    item_coords[138] = Vector2i(31, 6)  # Haunted Dreams (staff)
    item_coords[139] = Vector2i(0, 7)  # the Vigilant Eye (staff)
    item_coords[150] = Vector2i(1, 7)  # Secrets (staff)
    item_coords[151] = Vector2i(2, 7)  # Ered Luin (staff)
    item_coords[152] = Vector2i(3, 7)  # Evasion (staff)
    item_coords[153] = Vector2i(4, 7)  # Protection (staff)
    item_coords[154] = Vector2i(5, 7)  # Strength (staff)
    item_coords[155] = Vector2i(6, 7)  # Dexterity (staff)
    item_coords[156] = Vector2i(7, 7)  # Frost (staff)
    item_coords[157] = Vector2i(8, 7)  # Warmth (staff)
    item_coords[158] = Vector2i(9, 7)  # Accuracy (staff)
    item_coords[159] = Vector2i(10, 7)  # Free Action (staff)
    item_coords[160] = Vector2i(11, 7)  # Cowardice (staff)
    item_coords[161] = Vector2i(12, 7)  # the Shadow's Vanguard (staff)
    item_coords[162] = Vector2i(13, 7)  # Venom's End (staff)
    item_coords[171] = Vector2i(14, 7)  # the Laiquendi (staff)
    item_coords[191] = Vector2i(15, 7)  # Imprisonment (scroll)
    item_coords[192] = Vector2i(16, 7)  # Freedom (scroll)
    item_coords[193] = Vector2i(17, 7)  # Light (scroll)
    item_coords[195] = Vector2i(18, 7)  # Sanctity (scroll)
    item_coords[196] = Vector2i(19, 7)  # Understanding (scroll)
    item_coords[197] = Vector2i(20, 7)  # Revelations (scroll)
    item_coords[198] = Vector2i(21, 7)  # Treasures (scroll)
    item_coords[199] = Vector2i(22, 7)  # Foes (scroll)
    item_coords[200] = Vector2i(23, 7)  # Slumber (scroll)
    item_coords[201] = Vector2i(24, 7)  # Majesty (scroll)
    item_coords[202] = Vector2i(25, 7)  # Self Knowledge (scroll)
    item_coords[203] = Vector2i(26, 7)  # Warding (scroll)
    item_coords[204] = Vector2i(27, 7)  # Dismay (scroll)
    item_coords[206] = Vector2i(28, 7)  # Recharging (scroll)
    item_coords[210] = Vector2i(29, 7)  # Summoning (scroll)
    item_coords[211] = Vector2i(30, 7)  # Shadows (scroll)
    item_coords[220] = Vector2i(31, 7)  # Wand of Frost
    item_coords[221] = Vector2i(0, 8)  # Wand of Fire
    item_coords[222] = Vector2i(1, 8)  # Wand of Slowing
    item_coords[224] = Vector2i(2, 8)  # Wand of Fear
    item_coords[225] = Vector2i(3, 8)  # Wand of Sleep
    item_coords[240] = Vector2i(4, 8)  # Terror (horn)
    item_coords[241] = Vector2i(5, 8)  # Thunder (horn)
    item_coords[242] = Vector2i(6, 8)  # Force (horn)
    item_coords[243] = Vector2i(7, 8)  # Blasting (horn)
    item_coords[250] = Vector2i(8, 8)  # Challenge (horn)
    item_coords[251] = Vector2i(9, 8)  # Flute of the Fairy
    item_coords[316] = Vector2i(10, 8)  # Esgalduin
    item_coords[317] = Vector2i(11, 8)  # Clarity
    item_coords[318] = Vector2i(12, 8)  # Cordial of the Wise
    item_coords[321] = Vector2i(13, 8)  # Antidote
    item_coords[322] = Vector2i(14, 8)  # Quickness
    item_coords[323] = Vector2i(15, 8)  # Elemental Resistance
    item_coords[324] = Vector2i(16, 8)  # Shadows
    item_coords[327] = Vector2i(17, 8)  # Draught of Might
    item_coords[330] = Vector2i(18, 8)  # Starlight Elixir
    item_coords[345] = Vector2i(19, 8)  # Blindness (bad potion)
    item_coords[346] = Vector2i(20, 8)  # Confusion (bad potion)
    item_coords[350] = Vector2i(21, 8)  # Disconnection (bad potion)
    item_coords[381] = Vector2i(22, 8)  # Waymeal
    item_coords[399] = Vector2i(23, 8)  # Travel Bread
    item_coords[400] = Vector2i(24, 8)  # Dried Meat
    item_coords[401] = Vector2i(25, 8)  # Lembas
    item_coords[403] = Vector2i(26, 8)  # Cram
    item_coords[411] = Vector2i(27, 8)  # Mallorn Torch
    item_coords[414] = Vector2i(28, 8)  # Concentrated Waymeal
    item_coords[420] = Vector2i(29, 8)  # Rusted Helm
    item_coords[421] = Vector2i(30, 8)  # Worn Boots
    item_coords[422] = Vector2i(31, 8)  # Shattered Shield
    item_coords[451] = Vector2i(0, 9)  # Note
    item_coords[452] = Vector2i(1, 9)  # Note
    item_coords[453] = Vector2i(2, 9)  # Note
    item_coords[454] = Vector2i(3, 9)  # Note
    item_coords[455] = Vector2i(4, 9)  # Note
    item_coords[456] = Vector2i(5, 9)  # Note
    item_coords[457] = Vector2i(6, 9)  # Note
    item_coords[458] = Vector2i(7, 9)  # Note
    item_coords[459] = Vector2i(8, 9)  # Note
    item_coords[460] = Vector2i(9, 9)  # Note
    item_coords[461] = Vector2i(10, 9)  # Note
    item_coords[462] = Vector2i(11, 9)  # Note
    item_coords[463] = Vector2i(12, 9)  # Note
    item_coords[464] = Vector2i(13, 9)  # Note
    item_coords[465] = Vector2i(14, 9)  # Note
    item_coords[466] = Vector2i(15, 9)  # Note
    item_coords[467] = Vector2i(16, 9)  # Note
    item_coords[468] = Vector2i(17, 9)  # Note
    item_coords[469] = Vector2i(18, 9)  # Note
    item_coords[470] = Vector2i(19, 9)  # Note
    item_coords[471] = Vector2i(20, 9)  # Note
    item_coords[472] = Vector2i(21, 9)  # Note
    item_coords[473] = Vector2i(22, 9)  # Note
    item_coords[474] = Vector2i(23, 9)  # Note
    item_coords[475] = Vector2i(24, 9)  # Note
    item_coords[476] = Vector2i(25, 9)  # Note
    item_coords[477] = Vector2i(26, 9)  # Note
    item_coords[478] = Vector2i(27, 9)  # Note
    item_coords[479] = Vector2i(28, 9)  # Note
    item_coords[480] = Vector2i(29, 9)  # Note
    item_coords[481] = Vector2i(30, 9)  # Note
    item_coords[482] = Vector2i(31, 9)  # Note
    item_coords[483] = Vector2i(0, 10)  # Note
    item_coords[484] = Vector2i(1, 10)  # Note
    item_coords[485] = Vector2i(2, 10)  # Note
    item_coords[486] = Vector2i(3, 10)  # Note
    item_coords[487] = Vector2i(4, 10)  # Note
    item_coords[488] = Vector2i(5, 10)  # Note
    item_coords[489] = Vector2i(6, 10)  # Note
    item_coords[490] = Vector2i(7, 10)  # Note
    item_coords[492] = Vector2i(8, 10)  # Shattered Elven Mail
    item_coords[494] = Vector2i(9, 10)  # Twisted Shadow-plate
    item_coords[500] = Vector2i(10, 10)  # Thrain's Memory
    item_coords[501] = Vector2i(11, 10)  # Thrain's Memory
    item_coords[502] = Vector2i(12, 10)  # Thrain's Memory
    item_coords[503] = Vector2i(13, 10)  # Thrain's Memory
    item_coords[504] = Vector2i(14, 10)  # Thrain's Memory
    item_coords[505] = Vector2i(15, 10)  # Thrain's Memory
    item_coords[506] = Vector2i(16, 10)  # Thrain's Memory
    item_coords[507] = Vector2i(17, 10)  # Thrain's Memory
    item_coords[541] = Vector2i(18, 10)  # Thror's Coin
    item_coords[543] = Vector2i(19, 10)  # Dwarven Chronicle Page
    item_coords[544] = Vector2i(20, 10)  # Durin's Day Fragment
    item_coords[550] = Vector2i(21, 10)  # Prisoner's Account
    item_coords[551] = Vector2i(22, 10)  # Prisoner's Account
    item_coords[552] = Vector2i(23, 10)  # Orc Report
    item_coords[553] = Vector2i(24, 10)  # Orc Report
    item_coords[554] = Vector2i(25, 10)  # Historical Fragment
    item_coords[555] = Vector2i(26, 10)  # Historical Fragment
    item_coords[556] = Vector2i(27, 10)  # Necromancer Sighting
    item_coords[557] = Vector2i(28, 10)  # Necromancer Sighting

func _load_artifact_coords() -> void:
    artifact_coords[1] = Vector2i(29, 10)  # Ring of Barahir
    artifact_coords[7] = Vector2i(30, 10)  # Ring of the Nazgul
    artifact_coords[9] = Vector2i(31, 10)  # Ring of the Witch-King
    artifact_coords[20] = Vector2i(0, 11)  # Robe of Radagast
    artifact_coords[21] = Vector2i(1, 11)  # Robe of Galadriel
    artifact_coords[22] = Vector2i(2, 11)  # Robe of Rivendell
    artifact_coords[24] = Vector2i(3, 11)  # Leather of the Ranger
    artifact_coords[25] = Vector2i(4, 11)  # Leather of Halbarad
    artifact_coords[26] = Vector2i(5, 11)  # Woodman's Leather
    artifact_coords[28] = Vector2i(6, 11)  # Leather of Bard
    artifact_coords[29] = Vector2i(7, 11)  # Leather of the Beornings
    artifact_coords[32] = Vector2i(8, 11)  # Mail of Eol
    artifact_coords[34] = Vector2i(9, 11)  # Mail of Thranduil
    artifact_coords[35] = Vector2i(10, 11)  # Hauberk of Dain
    artifact_coords[36] = Vector2i(11, 11)  # Mithril Shirt
    artifact_coords[37] = Vector2i(12, 11)  # Corslet of the Tower Guard
    artifact_coords[39] = Vector2i(13, 11)  # Corslet of Celeborn
    artifact_coords[40] = Vector2i(14, 11)  # Shield of Elendil
    artifact_coords[41] = Vector2i(15, 11)  # Starlight (shield)
    artifact_coords[42] = Vector2i(16, 11)  # Shield of the Mark
    artifact_coords[43] = Vector2i(17, 11)  # Shield of Glorfindel
    artifact_coords[44] = Vector2i(18, 11)  # Shield of the Dunedain
    artifact_coords[45] = Vector2i(19, 11)  # Shield of Dale
    artifact_coords[46] = Vector2i(20, 11)  # Shield of Gil-galad
    artifact_coords[47] = Vector2i(21, 11)  # Shield of the White Tower
    artifact_coords[48] = Vector2i(22, 11)  # Shield of Dol Amroth
    artifact_coords[52] = Vector2i(23, 11)  # Morgul-blade
    artifact_coords[53] = Vector2i(24, 11)  # Sting
    artifact_coords[55] = Vector2i(25, 11)  # Sword of Harad
    artifact_coords[56] = Vector2i(26, 11)  # Sword of the Corsairs
    artifact_coords[58] = Vector2i(27, 11)  # Sword of Haldir
    artifact_coords[59] = Vector2i(28, 11)  # Westernesse (sword)
    artifact_coords[60] = Vector2i(29, 11)  # Sword of the Grey Company
    artifact_coords[64] = Vector2i(30, 11)  # Orcrist
    artifact_coords[65] = Vector2i(31, 11)  # Glamdring
    artifact_coords[66] = Vector2i(0, 12)  # Narsil
    artifact_coords[67] = Vector2i(1, 12)  # Sword of Isildur
    artifact_coords[71] = Vector2i(2, 12)  # Spear of Gondor
    artifact_coords[72] = Vector2i(3, 12)  # Guthwine
    artifact_coords[74] = Vector2i(4, 12)  # Herugrim
    artifact_coords[75] = Vector2i(5, 12)  # Blade of the Witch-Realm
    artifact_coords[76] = Vector2i(6, 12)  # Flame of the West
    artifact_coords[80] = Vector2i(7, 12)  # Ringil
    artifact_coords[81] = Vector2i(8, 12)  # Aiglos
    artifact_coords[83] = Vector2i(9, 12)  # Axe of the Eldar
    artifact_coords[85] = Vector2i(10, 12)  # Aeglos (spear)
    artifact_coords[86] = Vector2i(11, 12)  # Axe of the Eorlingas
    artifact_coords[87] = Vector2i(12, 12)  # Axe of the Galadhrim
    artifact_coords[89] = Vector2i(13, 12)  # Axe of Erebor
    artifact_coords[90] = Vector2i(14, 12)  # Morgul Axe
    artifact_coords[95] = Vector2i(15, 12)  # Mattock of Durin's Folk
    artifact_coords[96] = Vector2i(16, 12)  # Baruk Khazad (mattock)
    artifact_coords[99] = Vector2i(17, 12)  # Staff of Gondor
    artifact_coords[100] = Vector2i(18, 12)  # Staff of the Woodland Realm
    artifact_coords[101] = Vector2i(19, 12)  # Spider-bane (staff)
    artifact_coords[104] = Vector2i(20, 12)  # Staff of Gandalf
    artifact_coords[107] = Vector2i(21, 12)  # Mattock of the Longbeards
    artifact_coords[108] = Vector2i(22, 12)  # Mattock of Nogrod
    artifact_coords[117] = Vector2i(23, 12)  # Helm of Elrond
    artifact_coords[118] = Vector2i(24, 12)  # Helm of the Dunedain
    artifact_coords[119] = Vector2i(25, 12)  # Helm of the Oathbreaker
    artifact_coords[120] = Vector2i(26, 12)  # Helm of the Dragonslayer
    artifact_coords[121] = Vector2i(27, 12)  # Crown of Angmar
    artifact_coords[122] = Vector2i(28, 12)  # Crown of Thrain
    artifact_coords[123] = Vector2i(29, 12)  # Crown of Rivendell
    artifact_coords[131] = Vector2i(30, 12)  # Cloak of Lothlorien
    artifact_coords[132] = Vector2i(31, 12)  # Cloak of Elrond
    artifact_coords[134] = Vector2i(0, 13)  # Ranger's Cloak
    artifact_coords[137] = Vector2i(1, 13)  # Hame of the Werewolf
    artifact_coords[138] = Vector2i(2, 13)  # Fell of the Vampire
    artifact_coords[150] = Vector2i(3, 13)  # Black Arrow
    artifact_coords[154] = Vector2i(4, 13)  # Boots of Elrond
    artifact_coords[155] = Vector2i(5, 13)  # Boots of the Ranger
    artifact_coords[156] = Vector2i(6, 13)  # Boots of the Burglar
    artifact_coords[158] = Vector2i(7, 13)  # Boots of Gondor
    artifact_coords[159] = Vector2i(8, 13)  # Boots of the Helcaraxe
    artifact_coords[161] = Vector2i(9, 13)  # Gloves of the Archer
    artifact_coords[162] = Vector2i(10, 13)  # Gloves of the Smith
    artifact_coords[163] = Vector2i(11, 13)  # Gloves of the Healer
    artifact_coords[165] = Vector2i(12, 13)  # Gauntlets of the Iron Hills
    artifact_coords[166] = Vector2i(13, 13)  # Gauntlets of the Mark
    artifact_coords[167] = Vector2i(14, 13)  # Silverhand (gauntlets)
    artifact_coords[175] = Vector2i(15, 13)  # Map of Thrain
    artifact_coords[182] = Vector2i(16, 13)  # Ultimate Robe
    artifact_coords[183] = Vector2i(17, 13)  # Ultimate Leather
    artifact_coords[184] = Vector2i(18, 13)  # Ultimate Mail
    artifact_coords[185] = Vector2i(19, 13)  # Ultimate Plate
    artifact_coords[186] = Vector2i(20, 13)  # Ultimate Shield
    artifact_coords[187] = Vector2i(21, 13)  # Ultimate Sword
    artifact_coords[188] = Vector2i(22, 13)  # Ultimate Polearm
    artifact_coords[189] = Vector2i(23, 13)  # Ultimate Axe
    artifact_coords[190] = Vector2i(24, 13)  # Ultimate Staff
    artifact_coords[192] = Vector2i(25, 13)  # Ultimate Mattock
    artifact_coords[193] = Vector2i(26, 13)  # Ultimate Helm
    artifact_coords[194] = Vector2i(27, 13)  # Ultimate Cloak
    artifact_coords[196] = Vector2i(28, 13)  # Ultimate Boots
    artifact_coords[197] = Vector2i(29, 13)  # Ultimate Gloves
    artifact_coords[198] = Vector2i(30, 13)  # Ultimate Light
    artifact_coords[199] = Vector2i(31, 13)  # Crown of the Noldor
    artifact_coords[201] = Vector2i(0, 14)  # Ring of Mordor
    artifact_coords[204] = Vector2i(1, 14)  # Mantle of Stars
    artifact_coords[205] = Vector2i(2, 14)  # Helm of Erebor
    artifact_coords[206] = Vector2i(3, 14)  # Axe of Durin
    artifact_coords[207] = Vector2i(4, 14)  # Crown of the Smith
    artifact_coords[208] = Vector2i(5, 14)  # Shield of Erebor
    artifact_coords[209] = Vector2i(6, 14)  # Cloak of Shadow
    artifact_coords[211] = Vector2i(7, 14)  # Hadhafang
    artifact_coords[212] = Vector2i(8, 14)  # Noldorin Knife
    artifact_coords[218] = Vector2i(9, 14)  # Gauntlets of the Noldor
    artifact_coords[220] = Vector2i(10, 14)  # Staff of the Istari

func _load_player_coords() -> void:
    player_coords[0] = Vector2i(12, 3)  # Elf
    player_coords[1] = Vector2i(13, 3)  # Man
    player_coords[2] = Vector2i(14, 3)  # Dwarf
    player_coords[3] = Vector2i(15, 3)  # Istari

func _load_effect_coords() -> void:
	pass

func _load_char_mappings() -> void:
    # Map display characters to monster IDs for compatibility
    # When multiple monsters share a char, we pick a representative
    char_to_monster_id["M"] = 11   # Mirkwood Spider (also Great Spider, Web Spinner)
    char_to_monster_id["r"] = 12   # Giant Rat (also Black Squirrel)
    char_to_monster_id["b"] = 14   # Crebain (also Giant Bat)
    char_to_monster_id["&"] = 15   # Tanglethorn
    char_to_monster_id["o"] = 18   # Orc Scout (also other orcs)
    char_to_monster_id["O"] = 36   # Orc Captain
    char_to_monster_id["s"] = 19   # Swamp Adder
    char_to_monster_id["w"] = 21   # Warg Pup
    char_to_monster_id["W"] = 34   # Warg
    char_to_monster_id["T"] = 38   # Hill Troll
    char_to_monster_id["h"] = 51   # Dark Acolyte (humanoid)
    char_to_monster_id["G"] = 52   # Ghoul
    char_to_monster_id["g"] = 52   # Ghoul (lowercase)
    char_to_monster_id["H"] = 55   # Dark Sorcerer
    char_to_monster_id["Z"] = 73   # Zombie
    char_to_monster_id["z"] = 71   # Skeleton
    char_to_monster_id["S"] = 71   # Skeleton Warrior
    char_to_monster_id["p"] = 91   # Phantom
    char_to_monster_id["P"] = 91   # Phantom
    char_to_monster_id["W"] = 94   # Wraith
    char_to_monster_id["V"] = 113  # Vampire
    char_to_monster_id["U"] = 115  # Vampire Lord (unique)
    char_to_monster_id["@"] = 0    # Player (Elf)
    # Boss characters
    char_to_monster_id["N"] = 135  # Sauron, the Necromancer


# ============================================================================
# PUBLIC API
# ============================================================================

func get_terrain_coords(terrain_id: int, lit: bool = true) -> Vector2i:
    ## Get terrain tile coordinates. lit=true for visible, false for remembered.
    if terrain_coords.has(terrain_id):
        var data: Dictionary = terrain_coords[terrain_id]
        return data["light"] if lit else data["dark"]
    return Vector2i(0, 0)  # Default to first tile

func get_monster_coords(monster_id: int) -> Vector2i:
    ## Get monster tile coordinates by ID.
    if monster_coords.has(monster_id):
        return monster_coords[monster_id]
    return Vector2i(0, 0)

func get_monster_coords_for_char(display_char: String) -> Vector2i:
    ## Get monster tile coordinates by display character.
    if char_to_monster_id.has(display_char):
        var monster_id: int = char_to_monster_id[display_char]
        return get_monster_coords(monster_id)
    return Vector2i(0, 0)

func get_item_coords(item_id: int) -> Vector2i:
    ## Get item tile coordinates.
    if item_coords.has(item_id):
        return item_coords[item_id]
    return Vector2i(0, 0)

func get_artifact_coords(artifact_id: int) -> Vector2i:
    ## Get artifact tile coordinates.
    if artifact_coords.has(artifact_id):
        return artifact_coords[artifact_id]
    # Fall back to items
    return get_item_coords(artifact_id)

func get_player_coords(race_id: int) -> Vector2i:
    ## Get player tile coordinates by race.
    if player_coords.has(race_id):
        return player_coords[race_id]
    return Vector2i(0, 0)

func get_effect_coords(effect_id: int) -> Vector2i:
    ## Get effect/status tile coordinates.
    if effect_coords.has(effect_id):
        return effect_coords[effect_id]
    return Vector2i(0, 0)

func get_object_coords(object_id: int) -> Vector2i:
    ## Compatibility function - tries items then artifacts.
    # Quest artifacts (Ring/Key/Map of Thrain/Erebor) intentionally overlap
    # base object ids; force artifact visuals for this range.
    if object_id >= 175 and object_id <= 180 and artifact_coords.has(object_id):
        return artifact_coords[object_id]
    if item_coords.has(object_id):
        return item_coords[object_id]
    if artifact_coords.has(object_id):
        return artifact_coords[object_id]
    return Vector2i(0, 0)

# Legacy compatibility
func tile_enum_to_feature_id(tile_enum: int) -> int:
    return tile_enum
