extends Node
## DALL-E + DCSS tile mapper for Necromancer
## Auto-generated by integrate_terrain_v2.py
## Tileset: 32x32 grid of 64x64 tiles (2048x2048 pixels)

# Coordinate lookup tables
var terrain_coords: Dictionary = {}
var monster_coords: Dictionary = {}
var item_coords: Dictionary = {}
var artifact_coords: Dictionary = {}
var player_coords: Dictionary = {}
var effect_coords: Dictionary = {}
var layer_tile_kits: Dictionary = {}  # layer_name -> tile_enum -> {"light": Vector2i, "dark": Vector2i}

# Monster display char to ID mapping (for existing code compatibility)
var char_to_monster_id: Dictionary = {}

func _ready() -> void:
	_load_terrain_coords()
	_load_monster_coords()
	_load_item_coords()
	_load_artifact_coords()
	_load_player_coords()
	_load_effect_coords()
	_load_char_mappings()
	_load_layer_tile_kits()
	print("=== TileMapper Initialized (DALL-E Terrain + DCSS Entities) ===")
	print("Grid: 32x32, Tile size: 64x64")
	print("Total tiles loaded: ", terrain_coords.size() + monster_coords.size() + item_coords.size())
	print("Layer tile kits: ", layer_tile_kits.size(), " layers")

func _load_terrain_coords() -> void:
	# Format: terrain_coords[id] = {"light": Vector2i, "dark": Vector2i}
	terrain_coords[0] = {"light": Vector2i(0, 0), "dark": Vector2i(1, 0)}
	terrain_coords[1] = {"light": Vector2i(2, 0), "dark": Vector2i(3, 0)}
	terrain_coords[2] = {"light": Vector2i(4, 0), "dark": Vector2i(5, 0)}
	terrain_coords[3] = {"light": Vector2i(6, 0), "dark": Vector2i(7, 0)}
	terrain_coords[4] = {"light": Vector2i(8, 0), "dark": Vector2i(9, 0)}
	terrain_coords[5] = {"light": Vector2i(10, 0), "dark": Vector2i(11, 0)}
	terrain_coords[6] = {"light": Vector2i(12, 0), "dark": Vector2i(13, 0)}
	terrain_coords[7] = {"light": Vector2i(14, 0), "dark": Vector2i(15, 0)}
	terrain_coords[8] = {"light": Vector2i(16, 0), "dark": Vector2i(17, 0)}
	terrain_coords[9] = {"light": Vector2i(18, 0), "dark": Vector2i(19, 0)}
	terrain_coords[10] = {"light": Vector2i(20, 0), "dark": Vector2i(21, 0)}
	terrain_coords[11] = {"light": Vector2i(22, 0), "dark": Vector2i(23, 0)}
	terrain_coords[12] = {"light": Vector2i(24, 0), "dark": Vector2i(25, 0)}
	terrain_coords[13] = {"light": Vector2i(26, 0), "dark": Vector2i(27, 0)}
	terrain_coords[14] = {"light": Vector2i(28, 0), "dark": Vector2i(29, 0)}
	terrain_coords[15] = {"light": Vector2i(30, 0), "dark": Vector2i(31, 0)}
	terrain_coords[16] = {"light": Vector2i(0, 1), "dark": Vector2i(1, 1)}
	terrain_coords[17] = {"light": Vector2i(2, 1), "dark": Vector2i(3, 1)}
	terrain_coords[18] = {"light": Vector2i(4, 1), "dark": Vector2i(5, 1)}
	terrain_coords[19] = {"light": Vector2i(6, 1), "dark": Vector2i(7, 1)}
	terrain_coords[20] = {"light": Vector2i(8, 1), "dark": Vector2i(9, 1)}
	terrain_coords[21] = {"light": Vector2i(10, 1), "dark": Vector2i(11, 1)}
	terrain_coords[22] = {"light": Vector2i(12, 1), "dark": Vector2i(13, 1)}
	terrain_coords[23] = {"light": Vector2i(14, 1), "dark": Vector2i(15, 1)}
	terrain_coords[24] = {"light": Vector2i(16, 1), "dark": Vector2i(17, 1)}
	terrain_coords[25] = {"light": Vector2i(18, 1), "dark": Vector2i(19, 1)}
	terrain_coords[26] = {"light": Vector2i(20, 1), "dark": Vector2i(21, 1)}
	terrain_coords[27] = {"light": Vector2i(22, 1), "dark": Vector2i(23, 1)}
	terrain_coords[28] = {"light": Vector2i(24, 1), "dark": Vector2i(25, 1)}
	terrain_coords[29] = {"light": Vector2i(26, 1), "dark": Vector2i(27, 1)}
	terrain_coords[30] = {"light": Vector2i(28, 1), "dark": Vector2i(29, 1)}
	terrain_coords[31] = {"light": Vector2i(30, 1), "dark": Vector2i(31, 1)}
	terrain_coords[32] = {"light": Vector2i(0, 2), "dark": Vector2i(1, 2)}
	terrain_coords[33] = {"light": Vector2i(2, 2), "dark": Vector2i(3, 2)}
	terrain_coords[34] = {"light": Vector2i(4, 2), "dark": Vector2i(5, 2)}
	terrain_coords[35] = {"light": Vector2i(6, 2), "dark": Vector2i(7, 2)}
	terrain_coords[36] = {"light": Vector2i(8, 2), "dark": Vector2i(9, 2)}
	terrain_coords[37] = {"light": Vector2i(10, 2), "dark": Vector2i(11, 2)}
	terrain_coords[38] = {"light": Vector2i(12, 2), "dark": Vector2i(13, 2)}
	terrain_coords[39] = {"light": Vector2i(14, 2), "dark": Vector2i(15, 2)}
	terrain_coords[40] = {"light": Vector2i(16, 2), "dark": Vector2i(17, 2)}
	terrain_coords[41] = {"light": Vector2i(18, 2), "dark": Vector2i(19, 2)}
	terrain_coords[42] = {"light": Vector2i(20, 2), "dark": Vector2i(21, 2)}
	terrain_coords[43] = {"light": Vector2i(22, 2), "dark": Vector2i(23, 2)}
	terrain_coords[44] = {"light": Vector2i(24, 2), "dark": Vector2i(25, 2)}
	terrain_coords[45] = {"light": Vector2i(26, 2), "dark": Vector2i(27, 2)}
	terrain_coords[46] = {"light": Vector2i(28, 2), "dark": Vector2i(29, 2)}
	terrain_coords[47] = {"light": Vector2i(30, 2), "dark": Vector2i(31, 2)}
	terrain_coords[48] = {"light": Vector2i(0, 3), "dark": Vector2i(1, 3)}
	terrain_coords[49] = {"light": Vector2i(2, 3), "dark": Vector2i(3, 3)}
	terrain_coords[50] = {"light": Vector2i(4, 3), "dark": Vector2i(5, 3)}
	terrain_coords[51] = {"light": Vector2i(6, 3), "dark": Vector2i(7, 3)}
	terrain_coords[52] = {"light": Vector2i(8, 3), "dark": Vector2i(9, 3)}
	terrain_coords[53] = {"light": Vector2i(10, 3), "dark": Vector2i(11, 3)}
	terrain_coords[54] = {"light": Vector2i(12, 3), "dark": Vector2i(13, 3)}
	terrain_coords[55] = {"light": Vector2i(14, 3), "dark": Vector2i(15, 3)}
	terrain_coords[56] = {"light": Vector2i(16, 3), "dark": Vector2i(17, 3)}
	terrain_coords[57] = {"light": Vector2i(18, 3), "dark": Vector2i(19, 3)}
	terrain_coords[58] = {"light": Vector2i(20, 3), "dark": Vector2i(21, 3)}
	terrain_coords[59] = {"light": Vector2i(22, 3), "dark": Vector2i(23, 3)}
	terrain_coords[60] = {"light": Vector2i(24, 3), "dark": Vector2i(25, 3)}
	terrain_coords[61] = {"light": Vector2i(26, 3), "dark": Vector2i(27, 3)}
	terrain_coords[62] = {"light": Vector2i(28, 3), "dark": Vector2i(29, 3)}
	terrain_coords[63] = {"light": Vector2i(30, 3), "dark": Vector2i(31, 3)}
	terrain_coords[64] = {"light": Vector2i(0, 4), "dark": Vector2i(1, 4)}
	terrain_coords[65] = {"light": Vector2i(2, 4), "dark": Vector2i(3, 4)}
	terrain_coords[66] = {"light": Vector2i(4, 4), "dark": Vector2i(5, 4)}
	terrain_coords[67] = {"light": Vector2i(6, 4), "dark": Vector2i(7, 4)}
	terrain_coords[68] = {"light": Vector2i(8, 4), "dark": Vector2i(9, 4)}
	terrain_coords[69] = {"light": Vector2i(10, 4), "dark": Vector2i(11, 4)}
	terrain_coords[70] = {"light": Vector2i(12, 4), "dark": Vector2i(13, 4)}
	terrain_coords[71] = {"light": Vector2i(14, 4), "dark": Vector2i(15, 4)}
	terrain_coords[72] = {"light": Vector2i(16, 4), "dark": Vector2i(17, 4)}
	terrain_coords[73] = {"light": Vector2i(18, 4), "dark": Vector2i(19, 4)}
	terrain_coords[74] = {"light": Vector2i(20, 4), "dark": Vector2i(21, 4)}
	terrain_coords[75] = {"light": Vector2i(22, 4), "dark": Vector2i(23, 4)}
	terrain_coords[76] = {"light": Vector2i(24, 4), "dark": Vector2i(25, 4)}
	terrain_coords[77] = {"light": Vector2i(26, 4), "dark": Vector2i(27, 4)}
	terrain_coords[78] = {"light": Vector2i(28, 4), "dark": Vector2i(29, 4)}
	terrain_coords[79] = {"light": Vector2i(30, 4), "dark": Vector2i(31, 4)}
	terrain_coords[80] = {"light": Vector2i(0, 5), "dark": Vector2i(1, 5)}
	terrain_coords[81] = {"light": Vector2i(2, 5), "dark": Vector2i(3, 5)}
	terrain_coords[82] = {"light": Vector2i(4, 5), "dark": Vector2i(5, 5)}
	terrain_coords[83] = {"light": Vector2i(6, 5), "dark": Vector2i(7, 5)}
	terrain_coords[84] = {"light": Vector2i(8, 5), "dark": Vector2i(9, 5)}
	terrain_coords[85] = {"light": Vector2i(10, 5), "dark": Vector2i(11, 5)}
	terrain_coords[86] = {"light": Vector2i(12, 5), "dark": Vector2i(13, 5)}
	terrain_coords[87] = {"light": Vector2i(14, 5), "dark": Vector2i(15, 5)}

	# Level.gd Tile enum compatibility mappings
	# The game passes Level.Tile enum values (0-16), NOT terrain.txt IDs.
	# These MUST come AFTER the main load to override the wrong terrain.txt entries.
	# enum Tile { VOID=0, FLOOR=1, WALL=2, DOOR_CLOSED=3, DOOR_OPEN=4,
	#   STAIRS_DOWN=5, STAIRS_UP=6, CHASM=7, RUBBLE=8, FORGE=9, TRAP=10,
	#   TRAP_TRIGGERED=11, DOOR_LOCKED=12, DOOR_JAMMED=13, DOOR_SECRET=14,
	#   WATER=15, LAVA=16, VINE_FLOOR=17, POISON_STREAM=18,
	#   WEB=19, DARK_POOL=20, MORGUL_RUNE=21, SHADOW_BRAZIER=22,
	#   GLYPH_OF_WARDING=23, BONE_PILE=24, SHADOW_FLOOR=25, THRONE_DAIS=26 }
	# VOID(0) -> darkness(0) already correct at (0,0)/(1,0)
	# FLOOR(1) -> open floor(1) already correct at (2,0)/(3,0)
	terrain_coords[2] = {"light": Vector2i(22, 0), "dark": Vector2i(23, 0)}    # WALL ->  (terrain 11)
	terrain_coords[3] = {"light": Vector2i(0, 2), "dark": Vector2i(1, 2)}    # DOOR_CLOSED ->  (terrain 32)
	terrain_coords[4] = {"light": Vector2i(8, 0), "dark": Vector2i(9, 0)}    # DOOR_OPEN ->  (terrain 4)
	terrain_coords[5] = {"light": Vector2i(18, 18), "dark": Vector2i(19, 18)}    # STAIRS_DOWN -> DALL-E regen
	terrain_coords[6] = {"light": Vector2i(0, 5), "dark": Vector2i(1, 5)}    # STAIRS_UP ->  (terrain 80)
	terrain_coords[7] = {"light": Vector2i(2, 1), "dark": Vector2i(3, 1)}    # CHASM ->  (terrain 17)
	terrain_coords[8] = {"light": Vector2i(2, 0), "dark": Vector2i(3, 0)}    # RUBBLE ->  (terrain 1)
	terrain_coords[9] = {"light": Vector2i(2, 4), "dark": Vector2i(3, 4)}    # FORGE ->  (terrain 65)
	terrain_coords[10] = {"light": Vector2i(6, 1), "dark": Vector2i(7, 1)}    # TRAP ->  (terrain 19)
	terrain_coords[11] = {"light": Vector2i(16, 1), "dark": Vector2i(17, 1)}    # TRAP_TRIGGERED ->  (terrain 24)
	terrain_coords[12] = {"light": Vector2i(0, 2), "dark": Vector2i(1, 2)}    # DOOR_LOCKED -> same as DOOR_CLOSED (iron door)
	terrain_coords[13] = {"light": Vector2i(0, 2), "dark": Vector2i(1, 2)}    # DOOR_JAMMED -> same as DOOR_CLOSED (iron door)
	terrain_coords[14] = {"light": Vector2i(22, 0), "dark": Vector2i(23, 0)}    # DOOR_SECRET ->  (terrain 11)
	terrain_coords[15] = {"light": Vector2i(6, 3), "dark": Vector2i(7, 3)}    # WATER ->  (terrain 51)
	terrain_coords[16] = {"light": Vector2i(26, 0), "dark": Vector2i(27, 0)}    # LAVA ->  (terrain 13)
	terrain_coords[17] = {"light": Vector2i(16, 18), "dark": Vector2i(17, 18)}    # VINE_FLOOR -> DALL-E regen
	terrain_coords[18] = {"light": Vector2i(20, 18), "dark": Vector2i(21, 18)}    # POISON_STREAM -> DALL-E regen
	# Stream D: New layer terrain types (row 18)
	# These use placeholder coords until DALL-E sprites are generated
	terrain_coords[19] = {"light": Vector2i(0, 18), "dark": Vector2i(1, 18)}    # WEB -> DALL-E regen
	terrain_coords[20] = {"light": Vector2i(2, 18), "dark": Vector2i(3, 18)}    # DARK_POOL
	terrain_coords[21] = {"light": Vector2i(4, 18), "dark": Vector2i(5, 18)}    # MORGUL_RUNE
	terrain_coords[22] = {"light": Vector2i(6, 18), "dark": Vector2i(7, 18)}    # SHADOW_BRAZIER
	terrain_coords[23] = {"light": Vector2i(8, 18), "dark": Vector2i(9, 18)}    # GLYPH_OF_WARDING
	terrain_coords[24] = {"light": Vector2i(2, 0), "dark": Vector2i(3, 0)}    # BONE_PILE -> reuses RUBBLE sprite (row 18 placeholder blank)
	terrain_coords[25] = {"light": Vector2i(12, 18), "dark": Vector2i(13, 18)}  # SHADOW_FLOOR
	terrain_coords[26] = {"light": Vector2i(14, 18), "dark": Vector2i(15, 18)}  # THRONE_DAIS

func _load_monster_coords() -> void:
	# === Tier 1: Outer Pits ===
	monster_coords[11] = Vector2i(0, 24)  # Mirkwood Spider
	monster_coords[12] = Vector2i(1, 24)  # Giant Rat
	monster_coords[13] = Vector2i(2, 24)  # Black Squirrel
	monster_coords[14] = Vector2i(3, 24)  # Crebain
	monster_coords[15] = Vector2i(4, 24)  # Tanglethorn
	monster_coords[16] = Vector2i(5, 24)  # Giant Bat
	monster_coords[17] = Vector2i(6, 24)  # Web Spinner
	monster_coords[18] = Vector2i(7, 24)  # Orc Scout
	monster_coords[19] = Vector2i(8, 24)  # Swamp Adder
	monster_coords[20] = Vector2i(9, 24)  # Great Spider
	monster_coords[21] = Vector2i(10, 24)  # Warg Pup
	monster_coords[22] = Vector2i(11, 24)  # Broodmother
	monster_coords[31] = Vector2i(12, 24)  # Orc Slave
	# === Tier 2: Lower Halls ===
	monster_coords[32] = Vector2i(13, 24)  # Orc Soldier
	monster_coords[33] = Vector2i(14, 24)  # Orc Crossbowman
	monster_coords[34] = Vector2i(15, 24)  # Warg
	monster_coords[35] = Vector2i(16, 24)  # Orc Thrallmaster
	monster_coords[36] = Vector2i(17, 24)  # Orc Captain
	monster_coords[37] = Vector2i(18, 24)  # Warg Rider
	monster_coords[38] = Vector2i(19, 24)  # Hill Troll
	monster_coords[39] = Vector2i(20, 24)  # Gashnak Warg-lord
	monster_coords[40] = Vector2i(21, 24)  # Orc Warchief
	monster_coords[51] = Vector2i(22, 24)  # Dark Acolyte
	# === Tier 3: Dark Halls ===
	monster_coords[52] = Vector2i(23, 24)  # Ghoul
	monster_coords[53] = Vector2i(24, 24)  # Mirk-troll
	monster_coords[54] = Vector2i(25, 24)  # Easterling Warrior
	monster_coords[55] = Vector2i(26, 24)  # Dark Sorcerer
	monster_coords[56] = Vector2i(27, 24)  # Tortured Wretch
	monster_coords[57] = Vector2i(28, 24)  # Easterling Champion
	monster_coords[58] = Vector2i(29, 24)  # Ghast
	monster_coords[59] = Vector2i(30, 24)  # Karvag Torturer
	monster_coords[60] = Vector2i(31, 24)  # Master Sorcerer
	monster_coords[71] = Vector2i(0, 25)  # Skeleton
	# === Tier 4: Necropolis ===
	monster_coords[72] = Vector2i(1, 25)  # Skeleton Warrior
	# === Tier 3: Dark Halls ===
	monster_coords[73] = Vector2i(2, 25)  # Zombie
	# === Tier 4: Necropolis ===
	monster_coords[74] = Vector2i(3, 25)  # Wight
	monster_coords[75] = Vector2i(4, 25)  # Corpse-candle
	monster_coords[76] = Vector2i(5, 25)  # Necromancer Adept
	monster_coords[77] = Vector2i(6, 25)  # Barrow-wight
	monster_coords[78] = Vector2i(7, 25)  # Bone Golem
	monster_coords[79] = Vector2i(8, 25)  # Grishnakh
	# === Tier 3: Dark Halls ===
	monster_coords[80] = Vector2i(9, 25)  # Easterling Infiltrator
	# === Tier 4: Necropolis ===
	monster_coords[81] = Vector2i(10, 25)  # Cave Troll
	monster_coords[82] = Vector2i(11, 25)  # Dark Ritualist
	monster_coords[83] = Vector2i(12, 25)  # Corsair of Umbar
	monster_coords[84] = Vector2i(13, 25)  # Dunlending
	# === Tier 3: Dark Halls ===
	monster_coords[85] = Vector2i(14, 25)  # Tunnel Crawler
	# === Tier 4: Necropolis ===
	monster_coords[86] = Vector2i(15, 25)  # Pale Crawler
	monster_coords[87] = Vector2i(15, 24)  # Werewolf (uses Warg tile as placeholder)
	monster_coords[91] = Vector2i(16, 25)  # Phantom
	# === Tier 5: Pits of Despair ===
	monster_coords[92] = Vector2i(17, 25)  # Shadow
	monster_coords[93] = Vector2i(18, 25)  # Whispering Shade
	monster_coords[94] = Vector2i(19, 25)  # Wraith
	monster_coords[95] = Vector2i(20, 25)  # Fell Spirit
	monster_coords[96] = Vector2i(21, 25)  # Spectre
	monster_coords[97] = Vector2i(22, 25)  # Vampire Thrall
	monster_coords[98] = Vector2i(23, 25)  # Wailing Horror
	monster_coords[99] = Vector2i(24, 25)  # Uvatha
	# === Tier 4: Necropolis ===
	monster_coords[100] = Vector2i(25, 25)  # BN Acolyte
	# === Tier 5: Pits of Despair ===
	monster_coords[101] = Vector2i(26, 25)  # Haradrim Assassin
	monster_coords[102] = Vector2i(27, 25)  # Cave Worm
	monster_coords[103] = Vector2i(28, 25)  # Oathbreaker
	monster_coords[104] = Vector2i(29, 25)  # Morgul Sorcerer
	monster_coords[111] = Vector2i(30, 25)  # Black Numenorean
	# === Tier 6: Inner Sanctum ===
	monster_coords[112] = Vector2i(31, 25)  # Olog-hai
	monster_coords[113] = Vector2i(0, 26)  # Vampire
	monster_coords[114] = Vector2i(1, 26)  # Greater Wraith
	monster_coords[115] = Vector2i(2, 26)  # Vampire Lord
	monster_coords[116] = Vector2i(3, 26)  # Shadow Lord
	monster_coords[117] = Vector2i(4, 26)  # Maia Thrall
	monster_coords[118] = Vector2i(5, 26)  # Khamul
	monster_coords[131] = Vector2i(6, 26)  # Elite Olog-hai
	# === Tier 7: Throne Room ===
	monster_coords[132] = Vector2i(7, 26)  # Greater Shadow
	monster_coords[133] = Vector2i(8, 26)  # Void Wraith
	monster_coords[134] = Vector2i(9, 26)  # Thrain's Shade
	monster_coords[135] = Vector2i(10, 26)  # Sauron
	# === Tier 6: Inner Sanctum ===
	monster_coords[136] = Vector2i(11, 26)  # BN Lord
	# === Tier 7: Throne Room ===
	monster_coords[137] = Vector2i(12, 26)  # Mouth of Sauron
	# === Tier 8: Hallucinations ===
	monster_coords[301] = Vector2i(13, 26)  # Gandalf
	monster_coords[302] = Vector2i(14, 26)  # Thranduil
	monster_coords[303] = Vector2i(15, 26)  # Galadriel
	monster_coords[304] = Vector2i(16, 26)  # Elrond
	monster_coords[305] = Vector2i(17, 26)  # Thorin
	monster_coords[306] = Vector2i(18, 26)  # Beorn
	monster_coords[307] = Vector2i(19, 26)  # Radagast
	monster_coords[308] = Vector2i(20, 26)  # Eagle
	monster_coords[309] = Vector2i(21, 26)  # Great Elk
	monster_coords[310] = Vector2i(22, 26)  # Ent

func _load_item_coords() -> void:
	item_coords[0] = Vector2i(0, 11)  # <pile>
	item_coords[1] = Vector2i(1, 11)  # Serpentine Ring
	item_coords[2] = Vector2i(2, 11)  # Ring
	item_coords[3] = Vector2i(3, 11)  # Amulet
	item_coords[4] = Vector2i(4, 11)  # Pearl
	item_coords[5] = Vector2i(5, 11)  # Jewel
	item_coords[6] = Vector2i(6, 11)  # Necklace
	item_coords[19] = Vector2i(7, 11)  # Mighty Hammer
	item_coords[20] = Vector2i(8, 11)  # Massive Iron Crown
	item_coords[21] = Vector2i(9, 11)  # Elven Light
	item_coords[22] = Vector2i(10, 11)  # Wanderer's Robe
	item_coords[23] = Vector2i(11, 11)  # Ranger Leathers
	item_coords[26] = Vector2i(12, 11)  # Scout's Armor
	item_coords[27] = Vector2i(13, 11)  # Shadow-steel Armor
	item_coords[30] = Vector2i(14, 11)  # Gondor Corslet
	item_coords[31] = Vector2i(15, 11)  # Dwarven Hauberk
	item_coords[38] = Vector2i(16, 11)  # Mithril Corslet
	item_coords[40] = Vector2i(17, 11)  # Orc Skeleton
	item_coords[41] = Vector2i(18, 11)  # Human Skeleton
	item_coords[42] = Vector2i(19, 11)  # Elf Skeleton
	item_coords[43] = Vector2i(20, 11)  # Buckler
	item_coords[44] = Vector2i(21, 11)  # Tower Shield
	item_coords[46] = Vector2i(22, 11)  # Mithril Shield
	item_coords[56] = Vector2i(23, 11)  # Ranger's Knife
	item_coords[57] = Vector2i(24, 11)  # Orc-blade
	item_coords[58] = Vector2i(1, 17)  # Curved Sword (DALL-E regen)
	item_coords[59] = Vector2i(2, 17)  # Sylvan Blade
	item_coords[60] = Vector2i(25, 11)  # Woodland Blade
	item_coords[64] = Vector2i(26, 11)  # Longsword
	item_coords[67] = Vector2i(27, 11)  # Rohirrim Blade
	item_coords[68] = Vector2i(28, 11)  # Númenórean Blade
	item_coords[69] = Vector2i(29, 11)  # Mithril Sword
	item_coords[70] = Vector2i(30, 11)  # Mithril Great-blade
	item_coords[71] = Vector2i(31, 11)  # Hunting Spear
	item_coords[72] = Vector2i(0, 12)  # Tower Guard Spear
	item_coords[74] = Vector2i(1, 12)  # Morgul Glaive
	item_coords[76] = Vector2i(2, 12)  # Woodsman's Axe
	item_coords[77] = Vector2i(3, 12)  # Dwarven War-axe
	item_coords[81] = Vector2i(4, 12)  # Erebor Great-axe
	item_coords[86] = Vector2i(5, 12)  # Oak Staff
	item_coords[89] = Vector2i(6, 12)  # Dwarven Hammer
	item_coords[96] = Vector2i(7, 12)  # Miner's Spade
	item_coords[98] = Vector2i(8, 12)  # Dwarf Mattock
	item_coords[100] = Vector2i(9, 12)  # Iron Helm
	item_coords[101] = Vector2i(10, 12)  # Tower Helm
	item_coords[102] = Vector2i(11, 12)  # Dwarf Mask
	item_coords[103] = Vector2i(12, 12)  # Mithril Helm
	item_coords[104] = Vector2i(13, 12)  # Crown
	item_coords[106] = Vector2i(14, 12)  # Traveler's Cloak
	item_coords[107] = Vector2i(15, 12)  # Shadow Cloak
	item_coords[108] = Vector2i(16, 12)  # Wolf-Hame
	item_coords[109] = Vector2i(17, 12)  # Bat-Fell
	item_coords[110] = Vector2i(18, 12)  # Silvan Bow
	item_coords[111] = Vector2i(19, 12)  # Longbow
	item_coords[112] = Vector2i(20, 12)  # Dragon-horn Bow
	item_coords[116] = Vector2i(21, 12)  # Arrow
	item_coords[118] = Vector2i(22, 12)  # Sling
	item_coords[119] = Vector2i(23, 12)  # Fine Leather Sling
	item_coords[120] = Vector2i(24, 12)  # Sling Stone
	item_coords[122] = Vector2i(25, 12)  # Traveler's Boots
	item_coords[123] = Vector2i(26, 12)  # Iron Greaves
	item_coords[124] = Vector2i(27, 12)  # Pair of Mithril Greaves
	item_coords[125] = Vector2i(28, 12)  # Leather Gloves
	item_coords[126] = Vector2i(29, 12)  # Iron Gauntlets
	item_coords[127] = Vector2i(30, 12)  # Set of Mithril Gauntlets
	item_coords[128] = Vector2i(31, 12)  # Wooden Torch
	item_coords[129] = Vector2i(0, 13)  # Brass Lantern
	item_coords[130] = Vector2i(1, 13)  # Jewel-lamp
	item_coords[131] = Vector2i(2, 13)  # Star-glass
	item_coords[132] = Vector2i(3, 13)  # Last Chances
	item_coords[133] = Vector2i(4, 13)  # Constitution
	item_coords[134] = Vector2i(5, 13)  # Grace
	item_coords[135] = Vector2i(6, 13)  # Regeneration
	item_coords[136] = Vector2i(7, 13)  # Preservation
	item_coords[137] = Vector2i(8, 13)  # the Blessed Realm
	item_coords[138] = Vector2i(9, 13)  # Haunted Dreams
	item_coords[139] = Vector2i(10, 13)  # the Vigilant Eye
	item_coords[140] = Vector2i(3, 13)  # the Hearth (shares Last Chances sprite)
	item_coords[141] = Vector2i(5, 13)  # Clear Sight (shares Grace sprite)
	item_coords[142] = Vector2i(4, 13)  # Fortitude (shares Constitution sprite)
	item_coords[143] = Vector2i(8, 13)  # Starlight (shares Blessed Realm sprite)
	item_coords[144] = Vector2i(7, 13)  # the Stoneheart (shares Preservation sprite)
	item_coords[145] = Vector2i(8, 13)  # Lorien-light (shares Blessed Realm sprite)
	item_coords[150] = Vector2i(11, 13)  # Secrets
	item_coords[151] = Vector2i(12, 13)  # Ered Luin
	item_coords[152] = Vector2i(13, 13)  # Evasion
	item_coords[153] = Vector2i(14, 13)  # Protection
	item_coords[154] = Vector2i(15, 13)  # Strength
	item_coords[155] = Vector2i(16, 13)  # Dexterity
	item_coords[156] = Vector2i(17, 13)  # Frost
	item_coords[157] = Vector2i(18, 13)  # Warmth
	item_coords[158] = Vector2i(19, 13)  # Accuracy
	item_coords[159] = Vector2i(20, 13)  # Free Action
	item_coords[160] = Vector2i(21, 13)  # Cowardice
	item_coords[161] = Vector2i(22, 13)  # the Shadow's Vanguard
	item_coords[162] = Vector2i(23, 13)  # Venom's End
	item_coords[171] = Vector2i(24, 13)  # the Laiquendi
	item_coords[173] = Vector2i(11, 13)  # the Watchful (shares Secrets sprite)
	item_coords[174] = Vector2i(15, 13)  # Endurance (shares Strength sprite)
	item_coords[175] = Vector2i(24, 13)  # the Forester (shares Laiquendi sprite)
	item_coords[176] = Vector2i(12, 13)  # Iron Will (shares Ered Luin sprite)
	item_coords[177] = Vector2i(23, 13)  # the Greenwood (shares Venom's End sprite)
	item_coords[178] = Vector2i(15, 13)  # Durin's Folk (shares Strength sprite)
	item_coords[179] = Vector2i(16, 13)  # Noldor Memory (shares Dexterity sprite)
	item_coords[180] = Vector2i(9, 13)  # the Shadow-ward (shares Haunted Dreams sprite)
	item_coords[181] = Vector2i(17, 13)  # Wrathful Fire (shares Frost sprite)
	item_coords[191] = Vector2i(25, 13)  # Imprisonment
	item_coords[192] = Vector2i(26, 13)  # Freedom
	item_coords[193] = Vector2i(27, 13)  # Light
	item_coords[195] = Vector2i(28, 13)  # Sanctity
	item_coords[196] = Vector2i(29, 13)  # Understanding
	item_coords[197] = Vector2i(30, 13)  # Revelations
	item_coords[198] = Vector2i(31, 13)  # Treasures
	item_coords[199] = Vector2i(0, 14)  # Foes
	item_coords[200] = Vector2i(1, 14)  # Slumber
	item_coords[201] = Vector2i(2, 14)  # Majesty
	item_coords[202] = Vector2i(3, 14)  # Self Knowledge
	item_coords[203] = Vector2i(4, 14)  # Warding
	item_coords[204] = Vector2i(5, 14)  # Dismay
	item_coords[206] = Vector2i(6, 14)  # Recharging
	item_coords[210] = Vector2i(7, 14)  # Summoning
	item_coords[211] = Vector2i(8, 14)  # Shadows
	item_coords[220] = Vector2i(9, 14)  # Wand of Frost
	item_coords[221] = Vector2i(10, 14)  # Wand of Fire
	item_coords[222] = Vector2i(11, 14)  # Wand of Slowing
	item_coords[223] = Vector2i(12, 14)  # Wand of Light
	item_coords[224] = Vector2i(13, 14)  # Wand of Fear
	item_coords[225] = Vector2i(14, 14)  # Wand of Sleep
	item_coords[240] = Vector2i(15, 14)  # Terror
	item_coords[241] = Vector2i(16, 14)  # Thunder
	item_coords[242] = Vector2i(17, 14)  # Force
	item_coords[243] = Vector2i(18, 14)  # Blasting
	item_coords[250] = Vector2i(19, 14)  # Challenge
	item_coords[251] = Vector2i(20, 14)  # Flute of the Fairy
	item_coords[313] = Vector2i(21, 14)  # Miruvor
	item_coords[315] = Vector2i(22, 14)  # Orcish Liquor
	item_coords[316] = Vector2i(23, 14)  # Esgalduin
	item_coords[317] = Vector2i(24, 14)  # Clarity
	item_coords[318] = Vector2i(25, 14)  # Cordial of the Wise
	item_coords[319] = Vector2i(26, 14)  # Voice
	item_coords[320] = Vector2i(27, 14)  # True Sight
	item_coords[321] = Vector2i(28, 14)  # Antidote
	item_coords[322] = Vector2i(29, 14)  # Quickness
	item_coords[323] = Vector2i(30, 14)  # Elemental Resistance
	item_coords[324] = Vector2i(31, 14)  # Shadows
	item_coords[327] = Vector2i(0, 15)  # Draught of Might
	item_coords[328] = Vector2i(1, 15)  # Nimble-wine
	item_coords[329] = Vector2i(2, 15)  # Hardy-brew
	item_coords[330] = Vector2i(3, 15)  # Starlight Elixir
	item_coords[343] = Vector2i(4, 15)  # Slowness
	item_coords[344] = Vector2i(5, 15)  # Poison
	item_coords[345] = Vector2i(6, 15)  # Blindness
	item_coords[346] = Vector2i(7, 15)  # Confusion
	item_coords[348] = Vector2i(8, 15)  # Awkwardness
	item_coords[350] = Vector2i(9, 15)  # Disconnection
	item_coords[372] = Vector2i(10, 15)  # Small wooden chest
	item_coords[373] = Vector2i(11, 15)  # Small steel chest
	item_coords[374] = Vector2i(12, 15)  # Small jewelled chest
	item_coords[375] = Vector2i(13, 15)  # Large wooden chest
	item_coords[376] = Vector2i(14, 15)  # Large steel chest
	item_coords[377] = Vector2i(15, 15)  # Large jewelled chest
	item_coords[378] = Vector2i(16, 15)  # Finely wrapped present
	item_coords[380] = Vector2i(17, 15)  # Orc-rage Mushroom
	item_coords[381] = Vector2i(18, 15)  # Waymeal
	item_coords[382] = Vector2i(19, 15)  # Terror
	item_coords[383] = Vector2i(20, 15)  # Healer's Herb
	item_coords[384] = Vector2i(21, 15)  # Restoration
	item_coords[385] = Vector2i(22, 15)  # Emptiness
	item_coords[386] = Vector2i(23, 15)  # Visions
	item_coords[387] = Vector2i(24, 15)  # Entrancement
	item_coords[388] = Vector2i(25, 15)  # Weakness
	item_coords[389] = Vector2i(26, 15)  # Sickness
	item_coords[390] = Vector2i(27, 15)  # Athelas
	item_coords[399] = Vector2i(28, 15)  # Piece of Travel Bread
	item_coords[400] = Vector2i(29, 15)  # Strip of Dried Meat
	item_coords[401] = Vector2i(30, 15)  # Fragment of Lembas
	item_coords[402] = Vector2i(31, 15)  # Flask of oil
	item_coords[403] = Vector2i(0, 16)  # Cake of Cram
	item_coords[404] = Vector2i(1, 16)  # Pipe-weed
	item_coords[410] = Vector2i(2, 16)  # Piece of Mithril
	item_coords[411] = Vector2i(3, 16)  # Mallorn Torch
	item_coords[412] = Vector2i(4, 16)  # Concentrated Healer's Herb
	item_coords[413] = Vector2i(5, 16)  # Potent Athelas
	item_coords[414] = Vector2i(6, 16)  # Concentrated Waymeal
	item_coords[415] = Vector2i(7, 16)  # Potent Orc-rage Mushroom
	item_coords[416] = Vector2i(8, 16)  # Phosphorescent Moss
	item_coords[417] = Vector2i(9, 16)  # Vial of Torch Oil
	item_coords[418] = Vector2i(10, 16)  # Nightshade Cloak
	item_coords[420] = Vector2i(11, 16)  # Rusted Helm
	item_coords[421] = Vector2i(12, 16)  # Worn Boots
	item_coords[422] = Vector2i(13, 16)  # Shattered Shield
	# Mirkwood herbs (tval 80, svals 13-18) — reuse closest existing herb sprites
	item_coords[423] = Vector2i(8, 16)  # Silverbark Moss -> Phosphorescent Moss sprite (moss)
	item_coords[424] = Vector2i(27, 15)  # Nightshade Berry -> Athelas sprite (dark herb)
	item_coords[425] = Vector2i(20, 15)  # Thornvine Root -> Healer's Herb sprite (root/herb)
	item_coords[426] = Vector2i(20, 15)  # Moonpetal -> Healer's Herb sprite (petal/herb)
	item_coords[427] = Vector2i(17, 15)  # Spider-bane -> Orc-rage Mushroom sprite (potent herb)
	item_coords[428] = Vector2i(8, 16)  # Gloomcap -> Phosphorescent Moss sprite (fungus/mushroom)
	item_coords[451] = Vector2i(14, 16)  # Note
	item_coords[491] = Vector2i(15, 16)  # Broken Glowing Weapon
	item_coords[492] = Vector2i(16, 16)  # Shattered Elven Mail
	item_coords[493] = Vector2i(17, 16)  # Broken Strange Weapon
	item_coords[494] = Vector2i(18, 16)  # Twisted Shadow-plate
	item_coords[495] = Vector2i(19, 16)  # Broken Strange Jewelry
	item_coords[500] = Vector2i(20, 16)  # Thráin's Memory
	item_coords[510] = Vector2i(21, 16)  # Shadow Fragment
	item_coords[520] = Vector2i(22, 16)  # Ancient Glyph
	item_coords[530] = Vector2i(23, 16)  # Palantír Shard
	item_coords[540] = Vector2i(24, 16)  # Mithril Brooch
	item_coords[541] = Vector2i(25, 16)  # Thrór's Coin
	item_coords[542] = Vector2i(26, 16)  # Dragon-Touched Gem
	item_coords[543] = Vector2i(27, 16)  # Dwarven Chronicle Page
	item_coords[544] = Vector2i(28, 16)  # Durin's Day Fragment
	item_coords[550] = Vector2i(29, 16)  # Prisoner's Account
	item_coords[552] = Vector2i(30, 16)  # Orc Report
	item_coords[554] = Vector2i(31, 16)  # Historical Fragment
	item_coords[556] = Vector2i(0, 17)  # Necromancer Sighting
	# Duplicate items sharing canonical sprites
	item_coords[7] = Vector2i(2, 11)  # -> item_2
	item_coords[10] = Vector2i(2, 11)  # -> item_2
	item_coords[11] = Vector2i(3, 11)  # -> item_3
	item_coords[452] = Vector2i(14, 16)  # -> item_451
	item_coords[453] = Vector2i(14, 16)  # -> item_451
	item_coords[454] = Vector2i(14, 16)  # -> item_451
	item_coords[455] = Vector2i(14, 16)  # -> item_451
	item_coords[456] = Vector2i(14, 16)  # -> item_451
	item_coords[457] = Vector2i(14, 16)  # -> item_451
	item_coords[458] = Vector2i(14, 16)  # -> item_451
	item_coords[459] = Vector2i(14, 16)  # -> item_451
	item_coords[460] = Vector2i(14, 16)  # -> item_451
	item_coords[461] = Vector2i(14, 16)  # -> item_451
	item_coords[462] = Vector2i(14, 16)  # -> item_451
	item_coords[463] = Vector2i(14, 16)  # -> item_451
	item_coords[464] = Vector2i(14, 16)  # -> item_451
	item_coords[465] = Vector2i(14, 16)  # -> item_451
	item_coords[466] = Vector2i(14, 16)  # -> item_451
	item_coords[467] = Vector2i(14, 16)  # -> item_451
	item_coords[468] = Vector2i(14, 16)  # -> item_451
	item_coords[469] = Vector2i(14, 16)  # -> item_451
	item_coords[470] = Vector2i(14, 16)  # -> item_451
	item_coords[471] = Vector2i(14, 16)  # -> item_451
	item_coords[472] = Vector2i(14, 16)  # -> item_451
	item_coords[473] = Vector2i(14, 16)  # -> item_451
	item_coords[474] = Vector2i(14, 16)  # -> item_451
	item_coords[475] = Vector2i(14, 16)  # -> item_451
	item_coords[476] = Vector2i(14, 16)  # -> item_451
	item_coords[477] = Vector2i(14, 16)  # -> item_451
	item_coords[478] = Vector2i(14, 16)  # -> item_451
	item_coords[479] = Vector2i(14, 16)  # -> item_451
	item_coords[480] = Vector2i(14, 16)  # -> item_451
	item_coords[481] = Vector2i(14, 16)  # -> item_451
	item_coords[482] = Vector2i(14, 16)  # -> item_451
	item_coords[483] = Vector2i(14, 16)  # -> item_451
	item_coords[484] = Vector2i(14, 16)  # -> item_451
	item_coords[485] = Vector2i(14, 16)  # -> item_451
	item_coords[486] = Vector2i(14, 16)  # -> item_451
	item_coords[487] = Vector2i(14, 16)  # -> item_451
	item_coords[488] = Vector2i(14, 16)  # -> item_451
	item_coords[489] = Vector2i(14, 16)  # -> item_451
	item_coords[490] = Vector2i(14, 16)  # -> item_451
	item_coords[501] = Vector2i(20, 16)  # -> item_500
	item_coords[502] = Vector2i(20, 16)  # -> item_500
	item_coords[503] = Vector2i(20, 16)  # -> item_500
	item_coords[504] = Vector2i(20, 16)  # -> item_500
	item_coords[505] = Vector2i(20, 16)  # -> item_500
	item_coords[506] = Vector2i(20, 16)  # -> item_500
	item_coords[507] = Vector2i(20, 16)  # -> item_500
	item_coords[511] = Vector2i(21, 16)  # -> item_510
	item_coords[512] = Vector2i(21, 16)  # -> item_510
	item_coords[513] = Vector2i(21, 16)  # -> item_510
	item_coords[514] = Vector2i(21, 16)  # -> item_510
	item_coords[515] = Vector2i(21, 16)  # -> item_510
	item_coords[521] = Vector2i(22, 16)  # -> item_520
	item_coords[522] = Vector2i(22, 16)  # -> item_520
	item_coords[523] = Vector2i(22, 16)  # -> item_520
	item_coords[524] = Vector2i(22, 16)  # -> item_520
	item_coords[525] = Vector2i(22, 16)  # -> item_520
	item_coords[526] = Vector2i(22, 16)  # -> item_520
	item_coords[531] = Vector2i(23, 16)  # -> item_530
	item_coords[532] = Vector2i(23, 16)  # -> item_530
	item_coords[533] = Vector2i(23, 16)  # -> item_530
	item_coords[551] = Vector2i(29, 16)  # -> item_550
	item_coords[553] = Vector2i(30, 16)  # -> item_552
	item_coords[555] = Vector2i(31, 16)  # -> item_554
	item_coords[557] = Vector2i(0, 17)  # -> item_556

func _load_artifact_coords() -> void:
	# sword (22 artefacts)
	artifact_coords[52] = Vector2i(0, 19)  # 'Morgul-blade'
	artifact_coords[53] = Vector2i(0, 19)  # 'Sting'
	artifact_coords[54] = Vector2i(0, 19)  # 'Narsil Shard'
	artifact_coords[55] = Vector2i(0, 19)  # of Harad
	artifact_coords[56] = Vector2i(0, 19)  # of the Corsairs
	artifact_coords[58] = Vector2i(0, 19)  # of Haldir
	artifact_coords[59] = Vector2i(0, 19)  # 'Westernesse'
	artifact_coords[60] = Vector2i(0, 19)  # of the Grey Company
	artifact_coords[64] = Vector2i(0, 19)  # 'Orcrist'
	artifact_coords[65] = Vector2i(0, 19)  # 'Glamdring'
	artifact_coords[66] = Vector2i(0, 19)  # 'Narsil'
	artifact_coords[67] = Vector2i(0, 19)  # of Isildur
	artifact_coords[71] = Vector2i(0, 19)  # of Gondor
	artifact_coords[72] = Vector2i(0, 19)  # 'Gúthwinë'
	artifact_coords[74] = Vector2i(0, 19)  # 'Herugrim'
	artifact_coords[75] = Vector2i(0, 19)  # of the Witch-Realm
	artifact_coords[76] = Vector2i(0, 19)  # 'Flame of the West'
	artifact_coords[80] = Vector2i(0, 19)  # 'Ringil'
	artifact_coords[81] = Vector2i(0, 19)  # 'Aiglos'
	artifact_coords[83] = Vector2i(0, 19)  # of the Eldar
	artifact_coords[211] = Vector2i(0, 19)  # 'Hadhafang'
	artifact_coords[212] = Vector2i(0, 19)  # 'Noldorin Knife'

	# axe (6 artefacts)
	artifact_coords[92] = Vector2i(1, 19)  # of the Beornings
	artifact_coords[93] = Vector2i(1, 19)  # of the Iron Hills
	artifact_coords[94] = Vector2i(1, 19)  # of Azanulbizar
	artifact_coords[95] = Vector2i(1, 19)  # of Durin's Folk
	artifact_coords[96] = Vector2i(1, 19)  # 'Baruk Khazâd'
	artifact_coords[213] = Vector2i(1, 19)  # of Erebor

	# spear (8 artefacts)
	artifact_coords[85] = Vector2i(2, 19)  # 'Aeglos'
	artifact_coords[86] = Vector2i(2, 19)  # of the Eorlingas
	artifact_coords[87] = Vector2i(2, 19)  # of the Galadhrim
	artifact_coords[89] = Vector2i(2, 19)  # of Erebor
	artifact_coords[90] = Vector2i(2, 19)  # of Morgul
	artifact_coords[99] = Vector2i(2, 19)  # of Gondor
	artifact_coords[100] = Vector2i(2, 19)  # of the Woodland Realm
	artifact_coords[101] = Vector2i(2, 19)  # 'Spider-bane'

	# staff (1 artefacts)
	artifact_coords[104] = Vector2i(3, 19)  # of Gandalf

	# hammer (3 artefacts)
	artifact_coords[107] = Vector2i(4, 19)  # of the Longbeards
	artifact_coords[108] = Vector2i(4, 19)  # of Nogrod
	artifact_coords[214] = Vector2i(4, 19)  # 'Hammer of the Longbeards'

	# pickaxe (1 artefacts)
	artifact_coords[114] = Vector2i(5, 19)  # of Khazad-dûm

	# bow (8 artefacts)
	artifact_coords[142] = Vector2i(6, 19)  # of Lothlórien
	artifact_coords[143] = Vector2i(6, 19)  # 'Death's Whisper'
	artifact_coords[145] = Vector2i(6, 19)  # of the Galadhrim
	artifact_coords[146] = Vector2i(6, 19)  # of the Mark
	artifact_coords[148] = Vector2i(6, 19)  # of Dale
	artifact_coords[215] = Vector2i(6, 19)  # of Mirkwood
	artifact_coords[216] = Vector2i(6, 19)  # 'Black Bow of Mordor'
	artifact_coords[217] = Vector2i(6, 19)  # 'Bow of the Last Alliance'

	# arrow (1 artefacts)
	artifact_coords[150] = Vector2i(7, 19)  # 'Black Arrow'

	# ring (9 artefacts)
	artifact_coords[1] = Vector2i(8, 19)  # of Barahir
	artifact_coords[2] = Vector2i(8, 19)  # 'Vilya's Shard'
	artifact_coords[7] = Vector2i(8, 19)  # of the Nazgûl
	artifact_coords[175] = Vector2i(8, 19)  # of Thráin
	artifact_coords[176] = Vector2i(8, 19)  # of Thráin
	artifact_coords[177] = Vector2i(8, 19)  # of Thráin
	artifact_coords[178] = Vector2i(8, 19)  # of Thráin
	artifact_coords[218] = Vector2i(8, 19)  # of the Noldor
	artifact_coords[219] = Vector2i(8, 19)  # 'Ring of Mastery'

	# amulet (7 artefacts)
	artifact_coords[3] = Vector2i(9, 19)  # of the Woodland Realm
	artifact_coords[4] = Vector2i(9, 19)  # 'Nimrodel's Tear'
	artifact_coords[5] = Vector2i(9, 19)  # 'Evenstar'
	artifact_coords[6] = Vector2i(9, 19)  # of Girion
	artifact_coords[220] = Vector2i(9, 19)  # of the Istari
	artifact_coords[221] = Vector2i(9, 19)  # 'Black Necklace'
	artifact_coords[222] = Vector2i(9, 19)  # 'Star of the North'

	# robe (9 artefacts)
	artifact_coords[20] = Vector2i(10, 19)  # of Radagast
	artifact_coords[21] = Vector2i(10, 19)  # of Galadriel
	artifact_coords[22] = Vector2i(10, 19)  # of Rivendell
	artifact_coords[24] = Vector2i(10, 19)  # of the Ranger
	artifact_coords[25] = Vector2i(10, 19)  # of Halbarad
	artifact_coords[26] = Vector2i(10, 19)  # 'Woodman's Leather'
	artifact_coords[28] = Vector2i(10, 19)  # of Bard
	artifact_coords[29] = Vector2i(10, 19)  # of the Beornings
	artifact_coords[32] = Vector2i(10, 19)  # of Eöl

	# mail (8 artefacts)
	artifact_coords[34] = Vector2i(11, 19)  # of Thranduil
	artifact_coords[35] = Vector2i(11, 19)  # of Dáin
	artifact_coords[36] = Vector2i(11, 19)  # 'Mithril Shirt'
	artifact_coords[37] = Vector2i(11, 19)  # of the Tower Guard
	artifact_coords[39] = Vector2i(11, 19)  # of Celeborn
	artifact_coords[40] = Vector2i(11, 19)  # of Elendil
	artifact_coords[41] = Vector2i(11, 19)  # 'Starlight'
	artifact_coords[205] = Vector2i(11, 19)  # of Erebor

	# shield (7 artefacts)
	artifact_coords[42] = Vector2i(12, 19)  # of the Mark
	artifact_coords[43] = Vector2i(12, 19)  # of Glorfindel
	artifact_coords[44] = Vector2i(12, 19)  # of the Dúnedain
	artifact_coords[45] = Vector2i(12, 19)  # of Dale
	artifact_coords[46] = Vector2i(12, 19)  # of Gil-galad
	artifact_coords[47] = Vector2i(12, 19)  # of the White Tower
	artifact_coords[48] = Vector2i(12, 19)  # of Dol Amroth

	# helm (9 artefacts)
	artifact_coords[117] = Vector2i(13, 19)  # of Elrond
	artifact_coords[118] = Vector2i(13, 19)  # of the Dúnedain
	artifact_coords[119] = Vector2i(13, 19)  # of the Oathbreaker
	artifact_coords[120] = Vector2i(13, 19)  # of the Dragonslayer
	artifact_coords[121] = Vector2i(13, 19)  # of Angmar
	artifact_coords[122] = Vector2i(13, 19)  # of Thráin
	artifact_coords[123] = Vector2i(13, 19)  # of Rivendell
	artifact_coords[206] = Vector2i(13, 19)  # of Durin
	artifact_coords[207] = Vector2i(13, 19)  # 'Crown of the Smith'

	# crown (3 artefacts)
	artifact_coords[8] = Vector2i(14, 19)  # of Gondor
	artifact_coords[9] = Vector2i(14, 19)  # of the Witch-King
	artifact_coords[10] = Vector2i(14, 19)  # of the Dwarrowdelf

	# cloak (7 artefacts)
	artifact_coords[131] = Vector2i(15, 19)  # of Lothlórien
	artifact_coords[132] = Vector2i(15, 19)  # of Elrond
	artifact_coords[134] = Vector2i(15, 19)  # 'Ranger's Cloak'
	artifact_coords[137] = Vector2i(15, 19)  # of the Werewolf
	artifact_coords[138] = Vector2i(15, 19)  # of the Vampire
	artifact_coords[203] = Vector2i(15, 19)  # of Mordor
	artifact_coords[204] = Vector2i(15, 19)  # 'Mantle of Stars'

	# boots (6 artefacts)
	artifact_coords[154] = Vector2i(16, 19)  # of Elrond
	artifact_coords[155] = Vector2i(16, 19)  # of the Ranger
	artifact_coords[156] = Vector2i(16, 19)  # of the Burglar
	artifact_coords[158] = Vector2i(16, 19)  # of Gondor
	artifact_coords[159] = Vector2i(16, 19)  # of the Helcaraxë
	artifact_coords[210] = Vector2i(16, 19)  # of Lothlórien

	# gloves (8 artefacts)
	artifact_coords[161] = Vector2i(17, 19)  # of the Archer
	artifact_coords[162] = Vector2i(17, 19)  # of the Smith
	artifact_coords[163] = Vector2i(17, 19)  # of the Healer
	artifact_coords[165] = Vector2i(17, 19)  # of the Iron Hills
	artifact_coords[166] = Vector2i(17, 19)  # of the Mark
	artifact_coords[167] = Vector2i(17, 19)  # 'Silverhand'
	artifact_coords[208] = Vector2i(17, 19)  # of Erebor
	artifact_coords[209] = Vector2i(17, 19)  # of Shadow

	# light_source (6 artefacts)
	artifact_coords[170] = Vector2i(18, 19)  # 'Galadriel's Phial'
	artifact_coords[179] = Vector2i(18, 19)  # to Erebor
	artifact_coords[199] = Vector2i(18, 19)  # of the Noldor
	artifact_coords[200] = Vector2i(18, 19)  # 'Palantír'
	artifact_coords[201] = Vector2i(18, 19)  # of Mordor
	artifact_coords[202] = Vector2i(18, 19)  # 'Elendilmir'


func _load_player_coords() -> void:
	player_coords[0] = Vector2i(0, 6)  # Elf
	player_coords[1] = Vector2i(1, 6)  # Man
	player_coords[2] = Vector2i(2, 6)  # Dwarf
	player_coords[3] = Vector2i(3, 6)  # Istari
	player_coords[4] = Vector2i(4, 6)  # Hobbit
	player_coords[5] = Vector2i(5, 6)
	player_coords[6] = Vector2i(6, 6)
	player_coords[7] = Vector2i(7, 6)
	player_coords[8] = Vector2i(8, 6)
	player_coords[9] = Vector2i(9, 6)
	player_coords[10] = Vector2i(10, 6)
	player_coords[11] = Vector2i(11, 6)

func _load_effect_coords() -> void:
	effect_coords[0] = Vector2i(12, 6)
	effect_coords[1] = Vector2i(13, 6)
	effect_coords[2] = Vector2i(14, 6)
	effect_coords[3] = Vector2i(15, 6)
	effect_coords[4] = Vector2i(16, 6)
	effect_coords[5] = Vector2i(17, 6)
	effect_coords[6] = Vector2i(18, 6)
	effect_coords[7] = Vector2i(19, 6)
	effect_coords[8] = Vector2i(20, 6)
	effect_coords[9] = Vector2i(21, 6)
	effect_coords[10] = Vector2i(22, 6)
	effect_coords[11] = Vector2i(23, 6)
	effect_coords[12] = Vector2i(24, 6)
	effect_coords[13] = Vector2i(25, 6)
	effect_coords[14] = Vector2i(26, 6)
	effect_coords[15] = Vector2i(27, 6)
	effect_coords[16] = Vector2i(28, 6)
	effect_coords[17] = Vector2i(29, 6)
	effect_coords[18] = Vector2i(30, 6)
	effect_coords[19] = Vector2i(31, 6)

func _load_char_mappings() -> void:
	# Map display characters to monster IDs for compatibility
	char_to_monster_id["M"] = 11   # Mirkwood Spider
	char_to_monster_id["r"] = 12   # Giant Rat
	char_to_monster_id["b"] = 14   # Crebain
	char_to_monster_id["&"] = 15   # Tanglethorn
	char_to_monster_id["o"] = 18   # Orc Scout
	char_to_monster_id["O"] = 36   # Orc Captain
	char_to_monster_id["s"] = 19   # Swamp Adder
	char_to_monster_id["w"] = 21   # Warg Pup
	char_to_monster_id["W"] = 34   # Warg
	char_to_monster_id["T"] = 38   # Hill Troll
	char_to_monster_id["h"] = 51   # Dark Acolyte
	char_to_monster_id["G"] = 52   # Ghoul
	char_to_monster_id["g"] = 52   # Ghoul
	char_to_monster_id["H"] = 55   # Dark Sorcerer
	char_to_monster_id["Z"] = 73   # Zombie
	char_to_monster_id["z"] = 71   # Skeleton
	char_to_monster_id["S"] = 71   # Skeleton Warrior
	char_to_monster_id["p"] = 91   # Phantom
	char_to_monster_id["P"] = 91   # Phantom
	char_to_monster_id["V"] = 113  # Vampire
	char_to_monster_id["U"] = 115  # Vampire Lord
	char_to_monster_id["@"] = 0    # Player
	char_to_monster_id["N"] = 135  # Sauron


# ============================================================================
# LAYER TILE KITS — per-layer wall/floor/door/stairs sprites (rows 20-23)
# ============================================================================

func _load_layer_tile_kits() -> void:
	# Layer tile kit mapping: each layer overrides WALL, FLOOR, DOOR_CLOSED,
	# DOOR_OPEN, STAIRS_DOWN, STAIRS_UP with unique themed sprites.
	# Tile enum IDs: FLOOR=1, WALL=2, DOOR_CLOSED=3, DOOR_OPEN=4, STAIRS_DOWN=5, STAIRS_UP=6
	# Also applies to: DOOR_LOCKED=12, DOOR_JAMMED=13 (use door_closed), DOOR_SECRET=14 (use wall)
	#
	# Tileset layout per 12-col block:
	#   col+0/+1: wall L/D, col+2/+3: floor L/D, col+4/+5: door_closed L/D,
	#   col+6/+7: door_open L/D, col+8/+9: stairs_down L/D, col+10/+11: stairs_up L/D
	#
	# Row 20: outer_pits (0-11) + lower_halls (12-23)
	# Row 21: dark_halls (0-11) + necropolis (12-23)
	# Row 22: pits_of_despair (0-11) + inner_sanctum (12-23)
	# Row 23: throne_room (0-11)

	var layouts: Array = [
		{"name": "outer_pits",      "row": 20, "col": 0},
		{"name": "lower_halls",     "row": 20, "col": 12},
		{"name": "dark_halls",      "row": 21, "col": 0},
		{"name": "necropolis",      "row": 21, "col": 12},
		{"name": "pits_of_despair", "row": 22, "col": 0},
		{"name": "inner_sanctum",   "row": 22, "col": 12},
		{"name": "throne_room",     "row": 23, "col": 0},
	]

	# Tile type order within each 12-col block, mapped to Level.Tile enum IDs
	var tile_types: Array = [
		2,   # WALL
		1,   # FLOOR
		3,   # DOOR_CLOSED
		4,   # DOOR_OPEN
		5,   # STAIRS_DOWN
		6,   # STAIRS_UP
	]

	for layout in layouts:
		var kit: Dictionary = {}
		var row: int = layout["row"]
		var base_col: int = layout["col"]
		for i in range(tile_types.size()):
			var tile_id: int = tile_types[i]
			var lc: int = base_col + i * 2
			var dc: int = lc + 1
			kit[tile_id] = {"light": Vector2i(lc, row), "dark": Vector2i(dc, row)}
		# Also map locked/jammed doors to the layer's door_closed sprite
		kit[12] = kit[3].duplicate()  # DOOR_LOCKED -> door_closed
		kit[13] = kit[3].duplicate()  # DOOR_JAMMED -> door_closed
		kit[14] = kit[2].duplicate()  # DOOR_SECRET -> wall (hidden)
		layer_tile_kits[layout["name"]] = kit

# ============================================================================
# PUBLIC API
# ============================================================================

func get_layer_terrain_coords(terrain_id: int, layer_name: String, lit: bool = true) -> Vector2i:
	## Get layer-specific terrain coords. Falls back to default if layer has no override.
	if layer_name in layer_tile_kits:
		var kit: Dictionary = layer_tile_kits[layer_name]
		if terrain_id in kit:
			var data: Dictionary = kit[terrain_id]
			return data["light"] if lit else data["dark"]
	# Fallback to default terrain coords
	return get_terrain_coords(terrain_id, lit)

func get_terrain_coords(terrain_id: int, lit: bool = true) -> Vector2i:
	## Get terrain tile coordinates. lit=true for visible, false for remembered.
	if terrain_coords.has(terrain_id):
		var data: Dictionary = terrain_coords[terrain_id]
		return data["light"] if lit else data["dark"]
	return Vector2i(0, 0)  # Default to first tile

func get_monster_coords(monster_id: int) -> Vector2i:
	## Get monster tile coordinates by ID.
	if monster_coords.has(monster_id):
		return monster_coords[monster_id]
	return Vector2i(0, 0)

func get_monster_coords_for_char(display_char: String) -> Vector2i:
	## Get monster tile coordinates by display character.
	if char_to_monster_id.has(display_char):
		var monster_id: int = char_to_monster_id[display_char]
		return get_monster_coords(monster_id)
	return Vector2i(0, 0)

func get_item_coords(item_id: int) -> Vector2i:
	## Get item tile coordinates.
	if item_coords.has(item_id):
		return item_coords[item_id]
	return Vector2i(0, 0)

func get_artifact_coords(artifact_id: int) -> Vector2i:
	## Get artifact tile coordinates.
	if artifact_coords.has(artifact_id):
		return artifact_coords[artifact_id]
	# Fall back to items
	return get_item_coords(artifact_id)

func get_player_coords(race_id: int) -> Vector2i:
	## Get player tile coordinates by race.
	if player_coords.has(race_id):
		return player_coords[race_id]
	return Vector2i(0, 0)

## V2 player sprite lookup: race + house + gender -> tileset coords
## Layout: rows 6-9, cols 0-5 (light), cols 6-11 (dark)
## Row 6: Elf (h0,h1,h2), Row 7: Man (h3,h4,h5), Row 8: Dwarf (h6,h7,h8), Row 9: Hobbit (h9,h10,h11)
const PLAYER_V2_RACES := {
	"Elf":    {"row": 6, "houses": [0, 1, 2]},
	"Man":    {"row": 7, "houses": [3, 4, 5]},
	"Dwarf":  {"row": 8, "houses": [6, 7, 8]},
	"Hobbit": {"row": 9, "houses": [9, 10, 11]},
}

func get_player_coords_v2(race_name: String, house_id: int, gender: String = "male", lit: bool = true) -> Vector2i:
	## Get player v2 tile coordinates by race name, house, and gender.
	var race_info: Dictionary = PLAYER_V2_RACES.get(race_name, {})
	if race_info.is_empty():
		return Vector2i(0, 6)
	var row: int = race_info["row"]
	var houses: Array = race_info["houses"]
	var house_index: int = houses.find(house_id)
	if house_index == -1:
		house_index = 0
	# Each house has male + female = 2 cols
	var col: int = house_index * 2
	if gender == "female":
		col += 1
	if not lit:
		col += 6  # Dark variants at cols 6-11
	return Vector2i(col, row)

func get_effect_coords(effect_id: int) -> Vector2i:
	## Get effect/status tile coordinates.
	if effect_coords.has(effect_id):
		return effect_coords[effect_id]
	return Vector2i(0, 0)

func get_object_coords(object_id: int) -> Vector2i:
	## Compatibility function - tries items then artifacts.
	if item_coords.has(object_id):
		return item_coords[object_id]
	if artifact_coords.has(object_id):
		return artifact_coords[object_id]
	return Vector2i(0, 0)

# Legacy compatibility
func tile_enum_to_feature_id(tile_enum: int) -> int:
	return tile_enum
