extends Node
## DALL-E + DCSS tile mapper for Necromancer
## Auto-generated by integrate_terrain_v2.py
## Tileset: 32x32 grid of 64x64 tiles (2048x2048 pixels)

# Coordinate lookup tables
var terrain_coords: Dictionary = {}
var monster_coords: Dictionary = {}
var item_coords: Dictionary = {}
var artifact_coords: Dictionary = {}
var player_coords: Dictionary = {}
var effect_coords: Dictionary = {}

# Monster display char to ID mapping (for existing code compatibility)
var char_to_monster_id: Dictionary = {}

func _ready() -> void:
	_load_terrain_coords()
	_load_monster_coords()
	_load_item_coords()
	_load_artifact_coords()
	_load_player_coords()
	_load_effect_coords()
	_load_char_mappings()
	print("=== TileMapper Initialized (DALL-E Terrain + DCSS Entities) ===")
	print("Grid: 32x32, Tile size: 64x64")
	print("Total tiles loaded: ", terrain_coords.size() + monster_coords.size() + item_coords.size())

func _load_terrain_coords() -> void:
	# Format: terrain_coords[id] = {"light": Vector2i, "dark": Vector2i}
	terrain_coords[0] = {"light": Vector2i(0, 0), "dark": Vector2i(1, 0)}
	terrain_coords[1] = {"light": Vector2i(2, 0), "dark": Vector2i(3, 0)}
	terrain_coords[2] = {"light": Vector2i(4, 0), "dark": Vector2i(5, 0)}
	terrain_coords[3] = {"light": Vector2i(6, 0), "dark": Vector2i(7, 0)}
	terrain_coords[4] = {"light": Vector2i(8, 0), "dark": Vector2i(9, 0)}
	terrain_coords[5] = {"light": Vector2i(10, 0), "dark": Vector2i(11, 0)}
	terrain_coords[6] = {"light": Vector2i(12, 0), "dark": Vector2i(13, 0)}
	terrain_coords[7] = {"light": Vector2i(14, 0), "dark": Vector2i(15, 0)}
	terrain_coords[8] = {"light": Vector2i(16, 0), "dark": Vector2i(17, 0)}
	terrain_coords[9] = {"light": Vector2i(18, 0), "dark": Vector2i(19, 0)}
	terrain_coords[10] = {"light": Vector2i(20, 0), "dark": Vector2i(21, 0)}
	terrain_coords[11] = {"light": Vector2i(22, 0), "dark": Vector2i(23, 0)}
	terrain_coords[12] = {"light": Vector2i(24, 0), "dark": Vector2i(25, 0)}
	terrain_coords[13] = {"light": Vector2i(26, 0), "dark": Vector2i(27, 0)}
	terrain_coords[14] = {"light": Vector2i(28, 0), "dark": Vector2i(29, 0)}
	terrain_coords[15] = {"light": Vector2i(30, 0), "dark": Vector2i(31, 0)}
	terrain_coords[16] = {"light": Vector2i(0, 1), "dark": Vector2i(1, 1)}
	terrain_coords[17] = {"light": Vector2i(2, 1), "dark": Vector2i(3, 1)}
	terrain_coords[18] = {"light": Vector2i(4, 1), "dark": Vector2i(5, 1)}
	terrain_coords[19] = {"light": Vector2i(6, 1), "dark": Vector2i(7, 1)}
	terrain_coords[20] = {"light": Vector2i(8, 1), "dark": Vector2i(9, 1)}
	terrain_coords[21] = {"light": Vector2i(10, 1), "dark": Vector2i(11, 1)}
	terrain_coords[22] = {"light": Vector2i(12, 1), "dark": Vector2i(13, 1)}
	terrain_coords[23] = {"light": Vector2i(14, 1), "dark": Vector2i(15, 1)}
	terrain_coords[24] = {"light": Vector2i(16, 1), "dark": Vector2i(17, 1)}
	terrain_coords[25] = {"light": Vector2i(18, 1), "dark": Vector2i(19, 1)}
	terrain_coords[26] = {"light": Vector2i(20, 1), "dark": Vector2i(21, 1)}
	terrain_coords[27] = {"light": Vector2i(22, 1), "dark": Vector2i(23, 1)}
	terrain_coords[28] = {"light": Vector2i(24, 1), "dark": Vector2i(25, 1)}
	terrain_coords[29] = {"light": Vector2i(26, 1), "dark": Vector2i(27, 1)}
	terrain_coords[30] = {"light": Vector2i(28, 1), "dark": Vector2i(29, 1)}
	terrain_coords[31] = {"light": Vector2i(30, 1), "dark": Vector2i(31, 1)}
	terrain_coords[32] = {"light": Vector2i(0, 2), "dark": Vector2i(1, 2)}
	terrain_coords[33] = {"light": Vector2i(2, 2), "dark": Vector2i(3, 2)}
	terrain_coords[34] = {"light": Vector2i(4, 2), "dark": Vector2i(5, 2)}
	terrain_coords[35] = {"light": Vector2i(6, 2), "dark": Vector2i(7, 2)}
	terrain_coords[36] = {"light": Vector2i(8, 2), "dark": Vector2i(9, 2)}
	terrain_coords[37] = {"light": Vector2i(10, 2), "dark": Vector2i(11, 2)}
	terrain_coords[38] = {"light": Vector2i(12, 2), "dark": Vector2i(13, 2)}
	terrain_coords[39] = {"light": Vector2i(14, 2), "dark": Vector2i(15, 2)}
	terrain_coords[40] = {"light": Vector2i(16, 2), "dark": Vector2i(17, 2)}
	terrain_coords[41] = {"light": Vector2i(18, 2), "dark": Vector2i(19, 2)}
	terrain_coords[42] = {"light": Vector2i(20, 2), "dark": Vector2i(21, 2)}
	terrain_coords[43] = {"light": Vector2i(22, 2), "dark": Vector2i(23, 2)}
	terrain_coords[44] = {"light": Vector2i(24, 2), "dark": Vector2i(25, 2)}
	terrain_coords[45] = {"light": Vector2i(26, 2), "dark": Vector2i(27, 2)}
	terrain_coords[46] = {"light": Vector2i(28, 2), "dark": Vector2i(29, 2)}
	terrain_coords[47] = {"light": Vector2i(30, 2), "dark": Vector2i(31, 2)}
	terrain_coords[48] = {"light": Vector2i(0, 3), "dark": Vector2i(1, 3)}
	terrain_coords[49] = {"light": Vector2i(2, 3), "dark": Vector2i(3, 3)}
	terrain_coords[50] = {"light": Vector2i(4, 3), "dark": Vector2i(5, 3)}
	terrain_coords[51] = {"light": Vector2i(6, 3), "dark": Vector2i(7, 3)}
	terrain_coords[52] = {"light": Vector2i(8, 3), "dark": Vector2i(9, 3)}
	terrain_coords[53] = {"light": Vector2i(10, 3), "dark": Vector2i(11, 3)}
	terrain_coords[54] = {"light": Vector2i(12, 3), "dark": Vector2i(13, 3)}
	terrain_coords[55] = {"light": Vector2i(14, 3), "dark": Vector2i(15, 3)}
	terrain_coords[56] = {"light": Vector2i(16, 3), "dark": Vector2i(17, 3)}
	terrain_coords[57] = {"light": Vector2i(18, 3), "dark": Vector2i(19, 3)}
	terrain_coords[58] = {"light": Vector2i(20, 3), "dark": Vector2i(21, 3)}
	terrain_coords[59] = {"light": Vector2i(22, 3), "dark": Vector2i(23, 3)}
	terrain_coords[60] = {"light": Vector2i(24, 3), "dark": Vector2i(25, 3)}
	terrain_coords[61] = {"light": Vector2i(26, 3), "dark": Vector2i(27, 3)}
	terrain_coords[62] = {"light": Vector2i(28, 3), "dark": Vector2i(29, 3)}
	terrain_coords[63] = {"light": Vector2i(30, 3), "dark": Vector2i(31, 3)}
	terrain_coords[64] = {"light": Vector2i(0, 4), "dark": Vector2i(1, 4)}
	terrain_coords[65] = {"light": Vector2i(2, 4), "dark": Vector2i(3, 4)}
	terrain_coords[66] = {"light": Vector2i(4, 4), "dark": Vector2i(5, 4)}
	terrain_coords[67] = {"light": Vector2i(6, 4), "dark": Vector2i(7, 4)}
	terrain_coords[68] = {"light": Vector2i(8, 4), "dark": Vector2i(9, 4)}
	terrain_coords[69] = {"light": Vector2i(10, 4), "dark": Vector2i(11, 4)}
	terrain_coords[70] = {"light": Vector2i(12, 4), "dark": Vector2i(13, 4)}
	terrain_coords[71] = {"light": Vector2i(14, 4), "dark": Vector2i(15, 4)}
	terrain_coords[72] = {"light": Vector2i(16, 4), "dark": Vector2i(17, 4)}
	terrain_coords[73] = {"light": Vector2i(18, 4), "dark": Vector2i(19, 4)}
	terrain_coords[74] = {"light": Vector2i(20, 4), "dark": Vector2i(21, 4)}
	terrain_coords[75] = {"light": Vector2i(22, 4), "dark": Vector2i(23, 4)}
	terrain_coords[76] = {"light": Vector2i(24, 4), "dark": Vector2i(25, 4)}
	terrain_coords[77] = {"light": Vector2i(26, 4), "dark": Vector2i(27, 4)}
	terrain_coords[78] = {"light": Vector2i(28, 4), "dark": Vector2i(29, 4)}
	terrain_coords[79] = {"light": Vector2i(30, 4), "dark": Vector2i(31, 4)}
	terrain_coords[80] = {"light": Vector2i(0, 5), "dark": Vector2i(1, 5)}
	terrain_coords[81] = {"light": Vector2i(2, 5), "dark": Vector2i(3, 5)}
	terrain_coords[82] = {"light": Vector2i(4, 5), "dark": Vector2i(5, 5)}
	terrain_coords[83] = {"light": Vector2i(6, 5), "dark": Vector2i(7, 5)}
	terrain_coords[84] = {"light": Vector2i(8, 5), "dark": Vector2i(9, 5)}
	terrain_coords[85] = {"light": Vector2i(10, 5), "dark": Vector2i(11, 5)}
	terrain_coords[86] = {"light": Vector2i(12, 5), "dark": Vector2i(13, 5)}
	terrain_coords[87] = {"light": Vector2i(14, 5), "dark": Vector2i(15, 5)}

	# Level.gd Tile enum compatibility mappings
	# The game passes Level.Tile enum values (0-16), NOT terrain.txt IDs.
	# These MUST come AFTER the main load to override the wrong terrain.txt entries.
	# enum Tile { VOID=0, FLOOR=1, WALL=2, DOOR_CLOSED=3, DOOR_OPEN=4,
	#   STAIRS_DOWN=5, STAIRS_UP=6, CHASM=7, RUBBLE=8, FORGE=9, TRAP=10,
	#   TRAP_TRIGGERED=11, DOOR_LOCKED=12, DOOR_JAMMED=13, DOOR_SECRET=14,
	#   WATER=15, LAVA=16 }
	# VOID(0) -> darkness(0) already correct at (0,0)/(1,0)
	# FLOOR(1) -> open floor(1) already correct at (2,0)/(3,0)
	terrain_coords[2] = {"light": Vector2i(22, 0), "dark": Vector2i(23, 0)}    # WALL ->  (terrain 11)
	terrain_coords[3] = {"light": Vector2i(0, 2), "dark": Vector2i(1, 2)}    # DOOR_CLOSED ->  (terrain 32)
	terrain_coords[4] = {"light": Vector2i(8, 0), "dark": Vector2i(9, 0)}    # DOOR_OPEN ->  (terrain 4)
	terrain_coords[5] = {"light": Vector2i(2, 5), "dark": Vector2i(3, 5)}    # STAIRS_DOWN ->  (terrain 81)
	terrain_coords[6] = {"light": Vector2i(0, 5), "dark": Vector2i(1, 5)}    # STAIRS_UP ->  (terrain 80)
	terrain_coords[7] = {"light": Vector2i(2, 1), "dark": Vector2i(3, 1)}    # CHASM ->  (terrain 17)
	terrain_coords[8] = {"light": Vector2i(2, 0), "dark": Vector2i(3, 0)}    # RUBBLE ->  (terrain 1)
	terrain_coords[9] = {"light": Vector2i(2, 4), "dark": Vector2i(3, 4)}    # FORGE ->  (terrain 65)
	terrain_coords[10] = {"light": Vector2i(6, 1), "dark": Vector2i(7, 1)}    # TRAP ->  (terrain 19)
	terrain_coords[11] = {"light": Vector2i(16, 1), "dark": Vector2i(17, 1)}    # TRAP_TRIGGERED ->  (terrain 24)
	terrain_coords[12] = {"light": Vector2i(12, 0), "dark": Vector2i(13, 0)}    # DOOR_LOCKED ->  (terrain 6)
	terrain_coords[13] = {"light": Vector2i(14, 0), "dark": Vector2i(15, 0)}    # DOOR_JAMMED ->  (terrain 7)
	terrain_coords[14] = {"light": Vector2i(22, 0), "dark": Vector2i(23, 0)}    # DOOR_SECRET ->  (terrain 11)
	terrain_coords[15] = {"light": Vector2i(6, 3), "dark": Vector2i(7, 3)}    # WATER ->  (terrain 51)
	terrain_coords[16] = {"light": Vector2i(26, 0), "dark": Vector2i(27, 0)}    # LAVA ->  (terrain 13)

func _load_monster_coords() -> void:
	# Tier 1 monsters relocated to row 24 (rows 8-9 cols 0-11 used by player v2 sprites)
	monster_coords[11] = Vector2i(0, 24)   # Mirkwood Spider
	monster_coords[12] = Vector2i(1, 24)   # Giant Rat
	monster_coords[13] = Vector2i(2, 24)   # Black Squirrel
	monster_coords[14] = Vector2i(3, 24)   # Crebain
	monster_coords[15] = Vector2i(4, 24)   # Tanglethorn
	monster_coords[16] = Vector2i(5, 24)   # Giant Bat
	monster_coords[17] = Vector2i(6, 24)   # Web Spinner
	monster_coords[18] = Vector2i(7, 24)   # Orc Scout
	monster_coords[19] = Vector2i(8, 24)   # Swamp Adder
	monster_coords[20] = Vector2i(9, 24)   # Great Spider
	monster_coords[21] = Vector2i(10, 24)  # Warg Pup
	monster_coords[22] = Vector2i(11, 24)  # Broodmother
	monster_coords[31] = Vector2i(12, 24)  # Orc Slave
	monster_coords[32] = Vector2i(13, 8)
	monster_coords[33] = Vector2i(14, 8)
	monster_coords[34] = Vector2i(15, 8)
	monster_coords[35] = Vector2i(16, 8)
	monster_coords[36] = Vector2i(17, 8)
	monster_coords[37] = Vector2i(18, 8)
	monster_coords[38] = Vector2i(19, 8)
	monster_coords[39] = Vector2i(20, 8)
	monster_coords[40] = Vector2i(21, 8)
	monster_coords[51] = Vector2i(22, 8)
	monster_coords[52] = Vector2i(23, 8)
	monster_coords[53] = Vector2i(24, 8)
	monster_coords[54] = Vector2i(25, 8)
	monster_coords[55] = Vector2i(26, 8)
	monster_coords[56] = Vector2i(27, 8)
	monster_coords[57] = Vector2i(28, 8)
	monster_coords[58] = Vector2i(29, 8)
	monster_coords[59] = Vector2i(30, 8)
	monster_coords[60] = Vector2i(31, 8)
	monster_coords[71] = Vector2i(0, 9)
	monster_coords[72] = Vector2i(2, 9)
	monster_coords[73] = Vector2i(1, 9)
	monster_coords[74] = Vector2i(3, 9)
	monster_coords[75] = Vector2i(4, 9)
	monster_coords[76] = Vector2i(5, 9)
	monster_coords[77] = Vector2i(6, 9)
	monster_coords[78] = Vector2i(7, 9)
	monster_coords[79] = Vector2i(8, 9)
	monster_coords[91] = Vector2i(9, 9)
	monster_coords[92] = Vector2i(10, 9)
	monster_coords[93] = Vector2i(11, 9)
	monster_coords[94] = Vector2i(12, 9)
	monster_coords[95] = Vector2i(13, 9)
	monster_coords[96] = Vector2i(14, 9)
	monster_coords[97] = Vector2i(15, 9)
	monster_coords[98] = Vector2i(16, 9)
	monster_coords[99] = Vector2i(17, 9)
	monster_coords[111] = Vector2i(18, 9)
	monster_coords[112] = Vector2i(19, 9)
	monster_coords[113] = Vector2i(20, 9)
	monster_coords[114] = Vector2i(21, 9)
	monster_coords[115] = Vector2i(22, 9)
	monster_coords[116] = Vector2i(23, 9)
	monster_coords[117] = Vector2i(24, 9)
	monster_coords[118] = Vector2i(25, 9)
	monster_coords[131] = Vector2i(26, 9)
	monster_coords[132] = Vector2i(27, 9)
	monster_coords[133] = Vector2i(28, 9)
	monster_coords[134] = Vector2i(29, 9)
	monster_coords[135] = Vector2i(30, 9)
	monster_coords[301] = Vector2i(31, 9)
	monster_coords[302] = Vector2i(0, 10)
	monster_coords[303] = Vector2i(1, 10)
	monster_coords[304] = Vector2i(2, 10)
	monster_coords[305] = Vector2i(3, 10)
	monster_coords[306] = Vector2i(4, 10)
	monster_coords[307] = Vector2i(5, 10)
	monster_coords[308] = Vector2i(6, 10)
	monster_coords[309] = Vector2i(7, 10)
	monster_coords[310] = Vector2i(8, 10)

func _load_item_coords() -> void:
	item_coords[0] = Vector2i(0, 11)
	item_coords[1] = Vector2i(1, 11)
	item_coords[2] = Vector2i(2, 11)
	item_coords[3] = Vector2i(3, 11)
	item_coords[4] = Vector2i(4, 11)
	item_coords[5] = Vector2i(5, 11)
	item_coords[6] = Vector2i(6, 11)
	item_coords[7] = Vector2i(7, 11)
	item_coords[10] = Vector2i(8, 11)
	item_coords[11] = Vector2i(9, 11)
	item_coords[19] = Vector2i(10, 11)
	item_coords[20] = Vector2i(11, 11)
	item_coords[21] = Vector2i(12, 11)
	item_coords[22] = Vector2i(13, 11)
	item_coords[23] = Vector2i(14, 11)
	item_coords[26] = Vector2i(15, 11)
	item_coords[27] = Vector2i(16, 11)
	item_coords[30] = Vector2i(17, 11)
	item_coords[31] = Vector2i(18, 11)
	item_coords[38] = Vector2i(19, 11)
	item_coords[40] = Vector2i(20, 11)
	item_coords[41] = Vector2i(21, 11)
	item_coords[42] = Vector2i(22, 11)
	item_coords[43] = Vector2i(23, 11)
	item_coords[44] = Vector2i(24, 11)
	item_coords[46] = Vector2i(25, 11)
	item_coords[56] = Vector2i(26, 11)
	item_coords[57] = Vector2i(27, 11)
	item_coords[60] = Vector2i(28, 11)
	item_coords[64] = Vector2i(29, 11)
	item_coords[67] = Vector2i(30, 11)
	item_coords[68] = Vector2i(31, 11)
	item_coords[69] = Vector2i(0, 12)
	item_coords[70] = Vector2i(1, 12)
	item_coords[71] = Vector2i(2, 12)
	item_coords[72] = Vector2i(3, 12)
	item_coords[74] = Vector2i(4, 12)
	item_coords[76] = Vector2i(5, 12)
	item_coords[77] = Vector2i(6, 12)
	item_coords[81] = Vector2i(7, 12)
	item_coords[86] = Vector2i(8, 12)
	item_coords[89] = Vector2i(9, 12)
	item_coords[96] = Vector2i(10, 12)
	item_coords[98] = Vector2i(11, 12)
	item_coords[100] = Vector2i(12, 12)
	item_coords[101] = Vector2i(13, 12)
	item_coords[102] = Vector2i(14, 12)
	item_coords[103] = Vector2i(15, 12)
	item_coords[104] = Vector2i(16, 12)
	item_coords[106] = Vector2i(17, 12)
	item_coords[107] = Vector2i(18, 12)
	item_coords[108] = Vector2i(19, 12)
	item_coords[109] = Vector2i(20, 12)
	item_coords[110] = Vector2i(21, 12)
	item_coords[111] = Vector2i(22, 12)
	item_coords[112] = Vector2i(23, 12)
	item_coords[116] = Vector2i(24, 12)
	item_coords[122] = Vector2i(25, 12)
	item_coords[123] = Vector2i(26, 12)
	item_coords[124] = Vector2i(27, 12)
	item_coords[125] = Vector2i(28, 12)
	item_coords[126] = Vector2i(29, 12)
	item_coords[127] = Vector2i(30, 12)
	item_coords[128] = Vector2i(31, 12)
	item_coords[129] = Vector2i(0, 13)
	item_coords[130] = Vector2i(1, 13)
	item_coords[131] = Vector2i(2, 13)
	item_coords[132] = Vector2i(3, 13)
	item_coords[133] = Vector2i(4, 13)
	item_coords[134] = Vector2i(5, 13)
	item_coords[135] = Vector2i(6, 13)
	item_coords[136] = Vector2i(7, 13)
	item_coords[137] = Vector2i(8, 13)
	item_coords[138] = Vector2i(9, 13)
	item_coords[139] = Vector2i(10, 13)
	item_coords[150] = Vector2i(11, 13)
	item_coords[151] = Vector2i(12, 13)
	item_coords[152] = Vector2i(13, 13)
	item_coords[153] = Vector2i(14, 13)
	item_coords[154] = Vector2i(15, 13)
	item_coords[155] = Vector2i(16, 13)
	item_coords[156] = Vector2i(17, 13)
	item_coords[157] = Vector2i(18, 13)
	item_coords[158] = Vector2i(19, 13)
	item_coords[159] = Vector2i(20, 13)
	item_coords[160] = Vector2i(21, 13)
	item_coords[161] = Vector2i(22, 13)
	item_coords[162] = Vector2i(23, 13)
	item_coords[171] = Vector2i(24, 13)
	item_coords[191] = Vector2i(25, 13)
	item_coords[192] = Vector2i(26, 13)
	item_coords[193] = Vector2i(27, 13)
	item_coords[195] = Vector2i(28, 13)
	item_coords[196] = Vector2i(29, 13)
	item_coords[197] = Vector2i(30, 13)
	item_coords[198] = Vector2i(31, 13)
	item_coords[199] = Vector2i(0, 14)
	item_coords[200] = Vector2i(1, 14)
	item_coords[201] = Vector2i(2, 14)
	item_coords[202] = Vector2i(3, 14)
	item_coords[203] = Vector2i(4, 14)
	item_coords[204] = Vector2i(5, 14)
	item_coords[206] = Vector2i(6, 14)
	item_coords[210] = Vector2i(7, 14)
	item_coords[211] = Vector2i(8, 14)
	item_coords[220] = Vector2i(9, 14)
	item_coords[221] = Vector2i(10, 14)
	item_coords[222] = Vector2i(11, 14)
	item_coords[223] = Vector2i(12, 14)
	item_coords[224] = Vector2i(13, 14)
	item_coords[225] = Vector2i(14, 14)
	item_coords[240] = Vector2i(15, 14)
	item_coords[241] = Vector2i(16, 14)
	item_coords[242] = Vector2i(17, 14)
	item_coords[243] = Vector2i(18, 14)
	item_coords[250] = Vector2i(19, 14)
	item_coords[251] = Vector2i(20, 14)
	item_coords[313] = Vector2i(21, 14)
	item_coords[315] = Vector2i(22, 14)
	item_coords[316] = Vector2i(23, 14)
	item_coords[317] = Vector2i(24, 14)
	item_coords[318] = Vector2i(25, 14)
	item_coords[319] = Vector2i(26, 14)
	item_coords[320] = Vector2i(27, 14)
	item_coords[321] = Vector2i(28, 14)
	item_coords[322] = Vector2i(29, 14)
	item_coords[323] = Vector2i(30, 14)
	item_coords[324] = Vector2i(31, 14)
	item_coords[327] = Vector2i(0, 15)
	item_coords[328] = Vector2i(1, 15)
	item_coords[329] = Vector2i(2, 15)
	item_coords[330] = Vector2i(3, 15)
	item_coords[343] = Vector2i(4, 15)
	item_coords[344] = Vector2i(5, 15)
	item_coords[345] = Vector2i(6, 15)
	item_coords[346] = Vector2i(7, 15)
	item_coords[348] = Vector2i(8, 15)
	item_coords[350] = Vector2i(9, 15)
	item_coords[372] = Vector2i(10, 15)
	item_coords[373] = Vector2i(11, 15)
	item_coords[374] = Vector2i(12, 15)
	item_coords[375] = Vector2i(13, 15)
	item_coords[376] = Vector2i(14, 15)
	item_coords[377] = Vector2i(15, 15)
	item_coords[378] = Vector2i(16, 15)
	item_coords[380] = Vector2i(17, 15)
	item_coords[381] = Vector2i(18, 15)
	item_coords[382] = Vector2i(19, 15)
	item_coords[383] = Vector2i(20, 15)
	item_coords[384] = Vector2i(21, 15)
	item_coords[385] = Vector2i(22, 15)
	item_coords[386] = Vector2i(23, 15)
	item_coords[387] = Vector2i(24, 15)
	item_coords[388] = Vector2i(25, 15)
	item_coords[389] = Vector2i(26, 15)
	item_coords[390] = Vector2i(27, 15)
	item_coords[399] = Vector2i(28, 15)
	item_coords[400] = Vector2i(29, 15)
	item_coords[401] = Vector2i(30, 15)
	item_coords[402] = Vector2i(31, 15)
	item_coords[403] = Vector2i(0, 16)
	item_coords[404] = Vector2i(1, 16)
	item_coords[410] = Vector2i(2, 16)
	item_coords[411] = Vector2i(3, 16)
	item_coords[412] = Vector2i(4, 16)
	item_coords[413] = Vector2i(5, 16)
	item_coords[414] = Vector2i(6, 16)
	item_coords[415] = Vector2i(7, 16)
	item_coords[420] = Vector2i(8, 16)
	item_coords[421] = Vector2i(9, 16)
	item_coords[422] = Vector2i(10, 16)
	item_coords[451] = Vector2i(11, 16)
	item_coords[452] = Vector2i(12, 16)
	item_coords[453] = Vector2i(13, 16)
	item_coords[454] = Vector2i(14, 16)
	item_coords[455] = Vector2i(15, 16)
	item_coords[456] = Vector2i(16, 16)
	item_coords[457] = Vector2i(17, 16)
	item_coords[458] = Vector2i(18, 16)
	item_coords[459] = Vector2i(19, 16)
	item_coords[460] = Vector2i(20, 16)
	item_coords[461] = Vector2i(21, 16)
	item_coords[462] = Vector2i(22, 16)
	item_coords[463] = Vector2i(23, 16)
	item_coords[464] = Vector2i(24, 16)
	item_coords[465] = Vector2i(25, 16)
	item_coords[466] = Vector2i(26, 16)
	item_coords[467] = Vector2i(27, 16)
	item_coords[468] = Vector2i(28, 16)
	item_coords[469] = Vector2i(29, 16)
	item_coords[470] = Vector2i(30, 16)
	item_coords[471] = Vector2i(31, 16)
	item_coords[472] = Vector2i(0, 17)
	item_coords[473] = Vector2i(1, 17)
	item_coords[474] = Vector2i(2, 17)
	item_coords[475] = Vector2i(3, 17)
	item_coords[476] = Vector2i(4, 17)
	item_coords[477] = Vector2i(5, 17)
	item_coords[478] = Vector2i(6, 17)
	item_coords[479] = Vector2i(7, 17)
	item_coords[480] = Vector2i(8, 17)
	item_coords[481] = Vector2i(9, 17)
	item_coords[482] = Vector2i(10, 17)
	item_coords[483] = Vector2i(11, 17)
	item_coords[484] = Vector2i(12, 17)
	item_coords[485] = Vector2i(13, 17)
	item_coords[486] = Vector2i(14, 17)
	item_coords[487] = Vector2i(15, 17)
	item_coords[488] = Vector2i(16, 17)
	item_coords[489] = Vector2i(17, 17)
	item_coords[490] = Vector2i(18, 17)
	item_coords[491] = Vector2i(19, 17)
	item_coords[492] = Vector2i(20, 17)
	item_coords[493] = Vector2i(21, 17)
	item_coords[494] = Vector2i(22, 17)
	item_coords[495] = Vector2i(23, 17)
	item_coords[500] = Vector2i(24, 17)
	item_coords[501] = Vector2i(25, 17)
	item_coords[502] = Vector2i(26, 17)
	item_coords[503] = Vector2i(27, 17)
	item_coords[504] = Vector2i(28, 17)
	item_coords[505] = Vector2i(29, 17)
	item_coords[506] = Vector2i(30, 17)
	item_coords[507] = Vector2i(31, 17)
	item_coords[510] = Vector2i(0, 18)
	item_coords[511] = Vector2i(1, 18)
	item_coords[512] = Vector2i(2, 18)
	item_coords[513] = Vector2i(3, 18)
	item_coords[514] = Vector2i(4, 18)
	item_coords[515] = Vector2i(5, 18)
	item_coords[520] = Vector2i(6, 18)
	item_coords[521] = Vector2i(7, 18)
	item_coords[522] = Vector2i(8, 18)
	item_coords[523] = Vector2i(9, 18)
	item_coords[524] = Vector2i(10, 18)
	item_coords[525] = Vector2i(11, 18)
	item_coords[526] = Vector2i(12, 18)
	item_coords[530] = Vector2i(13, 18)
	item_coords[531] = Vector2i(14, 18)
	item_coords[532] = Vector2i(15, 18)
	item_coords[533] = Vector2i(16, 18)
	item_coords[540] = Vector2i(17, 18)
	item_coords[541] = Vector2i(18, 18)
	item_coords[542] = Vector2i(19, 18)
	item_coords[543] = Vector2i(20, 18)
	item_coords[544] = Vector2i(21, 18)
	item_coords[550] = Vector2i(22, 18)
	item_coords[551] = Vector2i(23, 18)
	item_coords[552] = Vector2i(24, 18)
	item_coords[553] = Vector2i(25, 18)
	item_coords[554] = Vector2i(26, 18)
	item_coords[555] = Vector2i(27, 18)
	item_coords[556] = Vector2i(28, 18)
	item_coords[557] = Vector2i(29, 18)

func _load_artifact_coords() -> void:
	artifact_coords[1] = Vector2i(0, 19)
	artifact_coords[2] = Vector2i(1, 19)
	artifact_coords[3] = Vector2i(2, 19)
	artifact_coords[4] = Vector2i(3, 19)
	artifact_coords[5] = Vector2i(4, 19)
	artifact_coords[6] = Vector2i(5, 19)
	artifact_coords[7] = Vector2i(6, 19)
	artifact_coords[8] = Vector2i(7, 19)
	artifact_coords[9] = Vector2i(8, 19)
	artifact_coords[10] = Vector2i(9, 19)
	artifact_coords[20] = Vector2i(10, 19)
	artifact_coords[21] = Vector2i(11, 19)
	artifact_coords[22] = Vector2i(12, 19)
	artifact_coords[24] = Vector2i(13, 19)
	artifact_coords[25] = Vector2i(14, 19)
	artifact_coords[26] = Vector2i(15, 19)
	artifact_coords[28] = Vector2i(16, 19)
	artifact_coords[29] = Vector2i(17, 19)
	artifact_coords[32] = Vector2i(18, 19)
	artifact_coords[34] = Vector2i(19, 19)
	artifact_coords[35] = Vector2i(20, 19)
	artifact_coords[36] = Vector2i(21, 19)
	artifact_coords[37] = Vector2i(22, 19)
	artifact_coords[39] = Vector2i(23, 19)
	artifact_coords[40] = Vector2i(24, 19)
	artifact_coords[41] = Vector2i(25, 19)
	artifact_coords[42] = Vector2i(26, 19)
	artifact_coords[43] = Vector2i(27, 19)
	artifact_coords[44] = Vector2i(28, 19)
	artifact_coords[45] = Vector2i(29, 19)
	artifact_coords[46] = Vector2i(30, 19)
	artifact_coords[47] = Vector2i(31, 19)
	artifact_coords[48] = Vector2i(0, 20)
	artifact_coords[52] = Vector2i(1, 20)
	artifact_coords[53] = Vector2i(2, 20)
	artifact_coords[54] = Vector2i(3, 20)
	artifact_coords[55] = Vector2i(4, 20)
	artifact_coords[56] = Vector2i(5, 20)
	artifact_coords[58] = Vector2i(6, 20)
	artifact_coords[59] = Vector2i(7, 20)
	artifact_coords[60] = Vector2i(8, 20)
	artifact_coords[64] = Vector2i(9, 20)
	artifact_coords[65] = Vector2i(10, 20)
	artifact_coords[66] = Vector2i(11, 20)
	artifact_coords[67] = Vector2i(12, 20)
	artifact_coords[71] = Vector2i(13, 20)
	artifact_coords[72] = Vector2i(14, 20)
	artifact_coords[74] = Vector2i(15, 20)
	artifact_coords[75] = Vector2i(16, 20)
	artifact_coords[76] = Vector2i(17, 20)
	artifact_coords[80] = Vector2i(18, 20)
	artifact_coords[81] = Vector2i(19, 20)
	artifact_coords[83] = Vector2i(20, 20)
	artifact_coords[85] = Vector2i(21, 20)
	artifact_coords[86] = Vector2i(22, 20)
	artifact_coords[87] = Vector2i(23, 20)
	artifact_coords[89] = Vector2i(24, 20)
	artifact_coords[90] = Vector2i(25, 20)
	artifact_coords[92] = Vector2i(26, 20)
	artifact_coords[93] = Vector2i(27, 20)
	artifact_coords[94] = Vector2i(28, 20)
	artifact_coords[95] = Vector2i(29, 20)
	artifact_coords[96] = Vector2i(30, 20)
	artifact_coords[99] = Vector2i(31, 20)
	artifact_coords[100] = Vector2i(0, 21)
	artifact_coords[101] = Vector2i(1, 21)
	artifact_coords[104] = Vector2i(2, 21)
	artifact_coords[107] = Vector2i(3, 21)
	artifact_coords[108] = Vector2i(4, 21)
	artifact_coords[114] = Vector2i(5, 21)
	artifact_coords[117] = Vector2i(6, 21)
	artifact_coords[118] = Vector2i(7, 21)
	artifact_coords[119] = Vector2i(8, 21)
	artifact_coords[120] = Vector2i(9, 21)
	artifact_coords[121] = Vector2i(10, 21)
	artifact_coords[122] = Vector2i(11, 21)
	artifact_coords[123] = Vector2i(12, 21)
	artifact_coords[131] = Vector2i(13, 21)
	artifact_coords[132] = Vector2i(14, 21)
	artifact_coords[134] = Vector2i(15, 21)
	artifact_coords[137] = Vector2i(16, 21)
	artifact_coords[138] = Vector2i(17, 21)
	artifact_coords[142] = Vector2i(18, 21)
	artifact_coords[143] = Vector2i(19, 21)
	artifact_coords[145] = Vector2i(20, 21)
	artifact_coords[146] = Vector2i(21, 21)
	artifact_coords[148] = Vector2i(22, 21)
	artifact_coords[150] = Vector2i(23, 21)
	artifact_coords[154] = Vector2i(24, 21)
	artifact_coords[155] = Vector2i(25, 21)
	artifact_coords[156] = Vector2i(26, 21)
	artifact_coords[158] = Vector2i(27, 21)
	artifact_coords[159] = Vector2i(28, 21)
	artifact_coords[161] = Vector2i(29, 21)
	artifact_coords[162] = Vector2i(30, 21)
	artifact_coords[163] = Vector2i(31, 21)
	artifact_coords[165] = Vector2i(0, 22)
	artifact_coords[166] = Vector2i(1, 22)
	artifact_coords[167] = Vector2i(2, 22)
	artifact_coords[170] = Vector2i(3, 22)
	artifact_coords[175] = Vector2i(4, 22)
	artifact_coords[176] = Vector2i(5, 22)
	artifact_coords[177] = Vector2i(6, 22)
	artifact_coords[178] = Vector2i(7, 22)
	artifact_coords[179] = Vector2i(8, 22)
	artifact_coords[180] = Vector2i(9, 22)
	artifact_coords[182] = Vector2i(10, 22)
	artifact_coords[183] = Vector2i(11, 22)
	artifact_coords[184] = Vector2i(12, 22)
	artifact_coords[185] = Vector2i(13, 22)
	artifact_coords[186] = Vector2i(14, 22)
	artifact_coords[187] = Vector2i(15, 22)
	artifact_coords[188] = Vector2i(16, 22)
	artifact_coords[189] = Vector2i(17, 22)
	artifact_coords[190] = Vector2i(18, 22)
	artifact_coords[191] = Vector2i(19, 22)
	artifact_coords[192] = Vector2i(20, 22)
	artifact_coords[193] = Vector2i(21, 22)
	artifact_coords[194] = Vector2i(22, 22)
	artifact_coords[195] = Vector2i(23, 22)
	artifact_coords[196] = Vector2i(24, 22)
	artifact_coords[197] = Vector2i(25, 22)
	artifact_coords[198] = Vector2i(26, 22)
	artifact_coords[199] = Vector2i(27, 22)
	artifact_coords[200] = Vector2i(28, 22)
	artifact_coords[201] = Vector2i(29, 22)
	artifact_coords[202] = Vector2i(30, 22)
	artifact_coords[203] = Vector2i(31, 22)
	artifact_coords[204] = Vector2i(0, 23)
	artifact_coords[205] = Vector2i(1, 23)
	artifact_coords[206] = Vector2i(2, 23)
	artifact_coords[207] = Vector2i(3, 23)
	artifact_coords[208] = Vector2i(4, 23)
	artifact_coords[209] = Vector2i(5, 23)
	artifact_coords[210] = Vector2i(6, 23)
	artifact_coords[211] = Vector2i(7, 23)
	artifact_coords[212] = Vector2i(8, 23)
	artifact_coords[213] = Vector2i(9, 23)
	artifact_coords[214] = Vector2i(10, 23)
	artifact_coords[215] = Vector2i(11, 23)
	artifact_coords[216] = Vector2i(12, 23)
	artifact_coords[217] = Vector2i(13, 23)
	artifact_coords[218] = Vector2i(14, 23)
	artifact_coords[219] = Vector2i(15, 23)
	artifact_coords[220] = Vector2i(16, 23)
	artifact_coords[221] = Vector2i(17, 23)
	artifact_coords[222] = Vector2i(18, 23)

func _load_player_coords() -> void:
	player_coords[0] = Vector2i(0, 6)  # Elf
	player_coords[1] = Vector2i(1, 6)  # Man
	player_coords[2] = Vector2i(2, 6)  # Dwarf
	player_coords[3] = Vector2i(3, 6)  # Istari
	player_coords[4] = Vector2i(4, 6)  # Hobbit
	player_coords[5] = Vector2i(5, 6)
	player_coords[6] = Vector2i(6, 6)
	player_coords[7] = Vector2i(7, 6)
	player_coords[8] = Vector2i(8, 6)
	player_coords[9] = Vector2i(9, 6)
	player_coords[10] = Vector2i(10, 6)
	player_coords[11] = Vector2i(11, 6)

func _load_effect_coords() -> void:
	effect_coords[0] = Vector2i(12, 6)
	effect_coords[1] = Vector2i(13, 6)
	effect_coords[2] = Vector2i(14, 6)
	effect_coords[3] = Vector2i(15, 6)
	effect_coords[4] = Vector2i(16, 6)
	effect_coords[5] = Vector2i(17, 6)
	effect_coords[6] = Vector2i(18, 6)
	effect_coords[7] = Vector2i(19, 6)
	effect_coords[8] = Vector2i(20, 6)
	effect_coords[9] = Vector2i(21, 6)
	effect_coords[10] = Vector2i(22, 6)
	effect_coords[11] = Vector2i(23, 6)
	effect_coords[12] = Vector2i(24, 6)
	effect_coords[13] = Vector2i(25, 6)
	effect_coords[14] = Vector2i(26, 6)
	effect_coords[15] = Vector2i(27, 6)
	effect_coords[16] = Vector2i(28, 6)
	effect_coords[17] = Vector2i(29, 6)
	effect_coords[18] = Vector2i(30, 6)
	effect_coords[19] = Vector2i(31, 6)

func _load_char_mappings() -> void:
	# Map display characters to monster IDs for compatibility
	char_to_monster_id["M"] = 11   # Mirkwood Spider
	char_to_monster_id["r"] = 12   # Giant Rat
	char_to_monster_id["b"] = 14   # Crebain
	char_to_monster_id["&"] = 15   # Tanglethorn
	char_to_monster_id["o"] = 18   # Orc Scout
	char_to_monster_id["O"] = 36   # Orc Captain
	char_to_monster_id["s"] = 19   # Swamp Adder
	char_to_monster_id["w"] = 21   # Warg Pup
	char_to_monster_id["W"] = 34   # Warg
	char_to_monster_id["T"] = 38   # Hill Troll
	char_to_monster_id["h"] = 51   # Dark Acolyte
	char_to_monster_id["G"] = 52   # Ghoul
	char_to_monster_id["g"] = 52   # Ghoul
	char_to_monster_id["H"] = 55   # Dark Sorcerer
	char_to_monster_id["Z"] = 73   # Zombie
	char_to_monster_id["z"] = 71   # Skeleton
	char_to_monster_id["S"] = 71   # Skeleton Warrior
	char_to_monster_id["p"] = 91   # Phantom
	char_to_monster_id["P"] = 91   # Phantom
	char_to_monster_id["V"] = 113  # Vampire
	char_to_monster_id["U"] = 115  # Vampire Lord
	char_to_monster_id["@"] = 0    # Player
	char_to_monster_id["N"] = 135  # Sauron


# ============================================================================
# PUBLIC API
# ============================================================================

func get_terrain_coords(terrain_id: int, lit: bool = true) -> Vector2i:
	## Get terrain tile coordinates. lit=true for visible, false for remembered.
	if terrain_coords.has(terrain_id):
		var data: Dictionary = terrain_coords[terrain_id]
		return data["light"] if lit else data["dark"]
	return Vector2i(0, 0)  # Default to first tile

func get_monster_coords(monster_id: int) -> Vector2i:
	## Get monster tile coordinates by ID.
	if monster_coords.has(monster_id):
		return monster_coords[monster_id]
	return Vector2i(0, 0)

func get_monster_coords_for_char(display_char: String) -> Vector2i:
	## Get monster tile coordinates by display character.
	if char_to_monster_id.has(display_char):
		var monster_id: int = char_to_monster_id[display_char]
		return get_monster_coords(monster_id)
	return Vector2i(0, 0)

func get_item_coords(item_id: int) -> Vector2i:
	## Get item tile coordinates.
	if item_coords.has(item_id):
		return item_coords[item_id]
	return Vector2i(0, 0)

func get_artifact_coords(artifact_id: int) -> Vector2i:
	## Get artifact tile coordinates.
	if artifact_coords.has(artifact_id):
		return artifact_coords[artifact_id]
	# Fall back to items
	return get_item_coords(artifact_id)

func get_player_coords(race_id: int) -> Vector2i:
	## Get player tile coordinates by race.
	if player_coords.has(race_id):
		return player_coords[race_id]
	return Vector2i(0, 0)

## V2 player sprite lookup: race + house + gender -> tileset coords
## Layout: rows 6-9, cols 0-5 (light), cols 6-11 (dark)
## Row 6: Elf (h0,h1,h2), Row 7: Man (h3,h4,h5), Row 8: Dwarf (h6,h7,h8), Row 9: Hobbit (h9,h10,h11)
const PLAYER_V2_RACES := {
	"Elf":    {"row": 6, "houses": [0, 1, 2]},
	"Man":    {"row": 7, "houses": [3, 4, 5]},
	"Dwarf":  {"row": 8, "houses": [6, 7, 8]},
	"Hobbit": {"row": 9, "houses": [9, 10, 11]},
}

func get_player_coords_v2(race_name: String, house_id: int, gender: String = "male", lit: bool = true) -> Vector2i:
	## Get player v2 tile coordinates by race name, house, and gender.
	var race_info: Dictionary = PLAYER_V2_RACES.get(race_name, {})
	if race_info.is_empty():
		return Vector2i(0, 6)
	var row: int = race_info["row"]
	var houses: Array = race_info["houses"]
	var house_index: int = houses.find(house_id)
	if house_index == -1:
		house_index = 0
	# Each house has male + female = 2 cols
	var col: int = house_index * 2
	if gender == "female":
		col += 1
	if not lit:
		col += 6  # Dark variants at cols 6-11
	return Vector2i(col, row)

func get_effect_coords(effect_id: int) -> Vector2i:
	## Get effect/status tile coordinates.
	if effect_coords.has(effect_id):
		return effect_coords[effect_id]
	return Vector2i(0, 0)

func get_object_coords(object_id: int) -> Vector2i:
	## Compatibility function - tries items then artifacts.
	if item_coords.has(object_id):
		return item_coords[object_id]
	if artifact_coords.has(object_id):
		return artifact_coords[object_id]
	return Vector2i(0, 0)

# Legacy compatibility
func tile_enum_to_feature_id(tile_enum: int) -> int:
	return tile_enum
